# EVDetect — MLflow Experiment Tracking

This notebook loads the finalized, saved models (produced by the multiclass and binary supervised-learning notebooks) and logs their functional and non-functional metrics to MLflow for centralized experiment tracking and comparison.

**Requires:** trained model artifacts present in a local `models/` folder, and `EVSE-B-PowerCombined.csv` in a local `data/` folder (see repository README).

In [ ]:
# --- Path configuration (edit if your folder layout differs) ---
MODELS_DIR = 'models/'   # folder containing saved .pkl / .json / .keras model files
DATA_PATH = 'data/EVSE-B-PowerCombined.csv'

In [1]:
# Import the necessary libraries and functions
import os
import joblib
import numpy as np
import pandas as pd
import mlflow
import mlflow.sklearn
import mlflow.tensorflow
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from mlflow.tracking import MlflowClient
import json
import warnings
import xgboost as xgb
import inspect
import tempfile
from mlflow.models.signature import infer_signature

2025-10-24 17:15:17.506561: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Set the tracking URI:

In [2]:
# Set the tracking uri
mlflow.set_tracking_uri('http://127.0.0.1:5000')

See all the active and deleted experiments:

In [ ]:
# Initialize MLflow client
client = MlflowClient()

# Get all experiments (including deleted ones)
all_experiments = client.search_experiments(view_type = mlflow.entities.ViewType.ALL)

print('All MLflow Experiments:')
print('=' * 80)

if not all_experiments:
    print('No experiments found')
else:
    for exp in all_experiments:
        status_emoji = '✅' if exp.lifecycle_stage == 'active' else '🗑️'
        print(f'{status_emoji} ID: {exp.experiment_id}')
        print(f'   Name: {exp.name}')
        print(f'   Status: {exp.lifecycle_stage}')

        # Count runs in this experiment
        try:
            runs = client.search_runs(
                experiment_ids = [exp.experiment_id],
                run_view_type = mlflow.entities.ViewType.ALL
            )
            print(f'   Runs: {len(runs)} total')
        except Exception:
            print(f'   Runs: Unable to count')
        print('-' * 40)

Permanently delete or restore any experiments and their runs:

In [5]:
# Initialize MLflow client
client = MlflowClient()

def completely_delete_experiment(experiment_name):
    """
    Completely delete an MLflow experiment and all its runs.
    This action cannot be undone.
    """
    try:
        # Get experiment by name
        experiment = client.get_experiment_by_name(experiment_name)
        
        if experiment is None:
            print(f"No experiment found with name: '{experiment_name}'")
            return False
            
        experiment_id = experiment.experiment_id
        print(f"Found experiment: '{experiment_name}' (ID: {experiment_id})")
        
        # Get all runs in this experiment (including deleted ones)
        runs = client.search_runs(
            experiment_ids = [experiment_id],
            run_view_type = mlflow.entities.ViewType.ALL  # Include active, deleted, and archived
        )
        
        print(f'Found {len(runs)} runs in this experiment')
        
        # Delete all runs first
        for run in runs:
            run_id = run.info.run_id
            try:
                if run.info.lifecycle_stage != 'deleted':
                    print(f"  Deleting run: {run_id}")
                    client.delete_run(run_id)
                else:
                    print(f'  Run already deleted: {run_id}')
            except Exception as e:
                print(f'  Warning: Could not delete run {run_id}: {e}')

        # Now delete the experiment
        if experiment.lifecycle_stage == 'active':
            print('Step 1: Moving experiment to deleted state...')
            client.delete_experiment(experiment_id)

        print('Step 2: Permanently deleting experiment...')
        client.delete_experiment(experiment_id)  # Second call for permanent deletion
        
        print(f"✅ Experiment '{experiment_name}' and all its runs have been permanently deleted")
        return True
        
    except Exception as e:
        print(f'❌ Error deleting experiment: {e}')
        return False

# Execute the deletion (commented out for safety - uncomment to run)
# completely_delete_experiment('Multiclass Classification (Charging State)')
# completely_delete_experiment('Multiclass Classification (Both States)')
# completely_delete_experiment('Binary Classification (Charging State)')
# completely_delete_experiment('Binary Classification (Both States)')

Create or get an existing active experiment:

In [37]:
# Initialize MLflow client
client = MlflowClient()

# Create or get experiment - handles deleted experiments with same name
experiment_name = 'Binary Classification (Both States)'

def create_or_get_experiment(name):
    """
    Create a new experiment or get existing active one.
    If a deleted experiment with the same name exists, restore it.
    """
    experiment = client.get_experiment_by_name(name)
    if experiment:
        if experiment.lifecycle_stage == 'active':
            print(f"Using existing active experiment: '{name}' (ID: {experiment.experiment_id})")
            return experiment.experiment_id
        else:
            print(f'Experiment exists but is not active (lifecycle_stage = {experiment.lifecycle_stage}). Attempting to restore...')
            client.restore_experiment(experiment.experiment_id)
            print(f"Restored experiment: '{name}' (ID: {experiment.experiment_id})")
            return experiment.experiment_id
    else:
        experiment_id = mlflow.create_experiment(name)
        print(f"Created new experiment: '{name}' (ID: {experiment_id})")
        return experiment_id

# Create or get the experiment and set it as active
experiment_id = create_or_get_experiment(experiment_name)
mlflow.set_experiment(experiment_name)
print(f"Active experiment: '{experiment_name}' (ID: {experiment_id})")

Created new experiment: 'Binary Classification (Both States)' (ID: 4)
Active experiment: 'Binary Classification (Both States)' (ID: 4)

# Multiclass Classification (Charging State)

In [3]:
# Set the experiment as active
mlflow.set_experiment('Multiclass Classification (Charging State)')

<Experiment: artifact_location='/Users/yannis/mlflow-artifacts/1', creation_time=1761295456430, experiment_id='1', last_update_time=1761297798102, lifecycle_stage='active', name='Multiclass Classification (Charging State)', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [4]:
# Load the sheet into a DataFrame
df = pd.read_csv(DATA_PATH)

# Display basic info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115298 entries, 0 to 115297
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           115298 non-null  object
 1   shunt_voltage  115298 non-null  int64
 2   bus_voltage_V  115298 non-null  float64
 3   current_mA     115298 non-null  int64
 4   power_mW       115298 non-null  int64
 5   State          115298 non-null  object
 6   Attack         115298 non-null  object
 7   Attack-Group   115298 non-null  object
 8   Label          115298 non-null  object
 9   interface      115298 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 8.8+ MB

In [5]:
# Print the first rows of the DataFrame
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp

In [6]:
# Define mapping dictionary
attack_mapping = {
    'syn-flood': 'DoS',
    'tcp-flood': 'DoS',
    'cryptojacking': 'Cryptojacking',
    'vuln-scan': 'Recon',
    'syn-stealth': 'Recon',
    'Backdoor': 'Backdoor',
    'none': 'Benign'
}

# Apply mapping to create 'Attack-New' column
df['Attack-New'] = df['Attack'].map(attack_mapping)

# Print the first rows of the DataFrame to verify the new column
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp,DoS
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp,DoS
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp,DoS
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp,DoS
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp,DoS

In [7]:
# Filter data for 'charging' state
df_charging = df[df['State'] == 'charging'].copy()

# Print the first few rows of the filtered DataFrame
df_charging.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
34884,12/26/2023 15:17,660,5.185,652,3380,charging,none,none,benign,none,Benign
34885,12/26/2023 15:17,769,5.189,675,3500,charging,none,none,benign,none,Benign
34886,12/26/2023 15:17,525,5.197,512,2660,charging,none,none,benign,none,Benign
34887,12/26/2023 15:17,690,5.181,642,3340,charging,none,none,benign,none,Benign
34888,12/26/2023 15:17,638,5.189,574,2780,charging,none,none,benign,none,Benign

In [8]:
# Calculate the number of instances for each unique value in 'Attack-New' column
df.loc[df['State'] == 'charging', 'Attack-New'].value_counts()

Attack-New
Backdoor         14172
Cryptojacking     8474
Benign            6947
Name: count, dtype: int64

In [9]:
# Select numerical features for classification (excluding categorical columns)
numerical_features = ['shunt_voltage', 'bus_voltage_V', 'current_mA', 'power_mW']

# Define features (X) and target variable (Y)
X = df_charging[numerical_features]
Y = df_charging['Attack-New']

In [10]:
# Split the dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y, shuffle = True)

In [11]:
# Split the training set into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.2, random_state = 42, stratify = Y_train, shuffle = True)

In [12]:
# Set the encoder 
label_encoder = LabelEncoder()

# Encode 'Attack-New' labels as numbers for each subset
# Note: This is done after splitting to avoid data leakage
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_val_encoded = label_encoder.transform(Y_val)
Y_test_encoded = label_encoder.transform(Y_test)

# Check what each number represents
print('Label encoder classes:', label_encoder.classes_)

Label encoder classes: ['Backdoor' 'Benign' 'Cryptojacking']

In [13]:
# Create the scaler
scaler = StandardScaler()

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Shape of the scaled data
print(f'Shape of X_train_scaled: {X_train_scaled.shape}')
print(f'Shape of X_val_scaled: {X_val_scaled.shape}')
print(f'Shape of X_test_scaled: {X_test_scaled.shape}')

Shape of X_train_scaled: (18939, 4)
Shape of X_val_scaled: (4735, 4)
Shape of X_test_scaled: (5919, 4)

In [ ]:
# Suppress specific warnings for cleaner output
warnings.filterwarnings('ignore', category = UserWarning)

# Models list
models_to_log = [
    ('KNN', MODELS_DIR + 'knn_multi_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('KNN SMOTE', MODELS_DIR + 'knn_multi_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('RBF SVM', MODELS_DIR + 'rbf_svm_multi_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('RBF SVM SMOTE', MODELS_DIR + 'rbf_svm_multi_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('XGBoost', MODELS_DIR + 'xgboost_multi_charging_best_model.json', 'xgboost', 'scaled', False),
    ('XGBoost SMOTE', MODELS_DIR + 'xgboost_multi_charging_smote_best_model.json', 'xgboost', 'scaled', True),
    ('Logistic Regression', MODELS_DIR + 'logistic_regression_multi_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('Logistic Regression SMOTE', MODELS_DIR + 'logistic_regression_multi_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('Random Forest', MODELS_DIR + 'random_forest_multi_charging_best_model.pkl', 'sklearn', 'original', False),
    ('Random Forest SMOTE', MODELS_DIR + 'random_forest_multi_charging_smote_best_model.pkl', 'sklearn', 'original', True),
    ('ANN', MODELS_DIR + 'ann_multi_charging_model.keras', 'keras', 'scaled', False),
    ('ANN SMOTE', MODELS_DIR + 'ann_multi_charging_smote_model.keras', 'keras', 'scaled', True),
    ('Stacking Classifier', MODELS_DIR + 'stacking_clf_multi_charging_best_model.pkl', 'sklearn', 'original', False)
]

# Load production results CSV
# Clean CSV columns for MLflow logging
df_prod = pd.read_csv('df_production_results_multi_charging.csv')

# Ensure numeric
for col in ['Prediction Time (sec)','F1 Macro', 'Memory Used (kB)', 'CPU Time (sec)', 'Physical Cores', 'Logical Cores', 'CPU % Used (Raw)',
            'CPU % Used (Normalized)','Model Size (MB)']:
    df_prod[col] = pd.to_numeric(df_prod[col], errors = 'coerce')

# Sanity checks
required_globals = ['X_train', 'X_test', 'X_test_scaled', 'Y_test_encoded', 'label_encoder']
missing = [g for g in required_globals if g not in globals()]
if missing:
    raise RuntimeError(f'Please ensure these globals exist before running: {missing}')

# Helper functions
def ensure_dataframe(X, ref_columns):
    if isinstance(X, np.ndarray):
        return pd.DataFrame(X, columns = list(ref_columns))
    if isinstance(X, pd.DataFrame):
        if list(X.columns) != list(ref_columns) and X.shape[1] == len(ref_columns):
            return pd.DataFrame(X.values, columns = list(ref_columns))
        return X
    raise ValueError('X must be numpy array or pandas DataFrame')

def model_includes_scaler(model):
    if isinstance(model, Pipeline):
        for step in model.named_steps.values():
            cls_name = step.__class__.__name__.lower()
            if 'scaler' in cls_name or 'standardscaler' in cls_name or 'minmax' in cls_name or 'preprocessor' in cls_name:
                return True
    return False

def _safe_params_dict(params: dict, prefix = ''):
    safe = {}
    for k, v in params.items():
        key = f'{prefix}{k}'
        if isinstance(v, (str, int, float, bool)) or v is None:
            safe[key] = v
        else:
            try:
                s = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
                safe[key] = s[:200]
            except Exception:
                safe[key] = str(type(v))
    return safe


def keras_params_summary(model: keras.Model):
    params = {}
    try:
        params['keras_total_params'] = model.count_params()
    except Exception:
        params['keras_total_params'] = None
    params['keras_layers_count'] = len(model.layers)
    for i, layer in enumerate(model.layers):
        try:
            cfg = layer.get_config()
        except Exception:
            cfg = {}
        params[f'layer_{i}_class'] = layer.__class__.__name__
        if 'units' in cfg:
            params[f'layer_{i}_units'] = cfg.get('units')
        if 'activation' in cfg:
            params[f'layer_{i}_activation'] = cfg.get('activation')
    try:
        opt = model.optimizer.get_config()
        params['optimizer'] = model.optimizer.__class__.__name__
        for k, v in opt.items():
            params[f'opt_{k}'] = v if isinstance(v, (str, int, float, bool)) else str(v)
    except Exception:
        pass
    try:
        params['loss'] = model.loss if not callable(model.loss) else str(model.loss)
    except Exception:
        pass
    return params

def extract_xgb_from_pipeline(m):
    if not isinstance(m, Pipeline):
        return None
    for step in m.named_steps.values():
        cls = step.__class__.__name__.lower()
        if 'xgb' in cls or hasattr(step, 'get_xgb_params'):
            return step
    return None

def safe_head_example(X, n = 8):
    try:
        if isinstance(X, pd.DataFrame):
            return X.head(n)
        if isinstance(X, np.ndarray):
            return pd.DataFrame(X[:n], columns = X_train.columns)
    except Exception:
        pass
    return None

def safe_predict_for_signature(model, X_example, framework):
    try:
        fw = (framework or '').lower()
        if fw == 'keras':
            preds = model.predict(X_example, verbose = 0)
            return preds
        elif fw == 'xgboost':
            if isinstance(model, xgb.core.Booster):
                d = xgb.DMatrix(X_example)
                preds = model.predict(d)
                return preds
            else:
                if hasattr(model, 'predict'):
                    return model.predict(X_example)
        else:
            return model.predict(X_example)
    except Exception:
        return None

def safe_log_params_iter(obj, prefix = ''):
    safe = {}
    try:
        gp = obj.get_params()
        for k, v in gp.items():
            try:
                if isinstance(v, (list, dict)):
                    safe[f'{prefix}{k}'] = json.dumps(v)[:400]
                elif hasattr(v, '__name__') and getattr(v, '__name__'):
                    safe[f'{prefix}{k}'] = getattr(v, '__name__')
                else:
                    safe[f'{prefix}{k}'] = v
            except Exception:
                safe[f'{prefix}{k}'] = str(type(v))
    except Exception:
        pass
    return safe

def mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = None):
    fw = (framework or '').lower()
    example_df = safe_head_example(X_example) if X_example is not None else None

    input_example_np = None
    signature = None
    input_example = None

    if example_df is not None:
        input_example_np = example_df.values if isinstance(example_df, pd.DataFrame) else example_df
        input_example = input_example_np
        preds = safe_predict_for_signature(model, input_example_np, fw)
        try:
            signature = infer_signature(input_example_np, preds) if preds is not None else infer_signature(input_example_np, None)
        except Exception:
            signature = None

    with tempfile.TemporaryDirectory(prefix = 'mlflow_model_') as tmp_path:
        try:
            if fw == 'keras':
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                # Skip passing input_example here to avoid MLflow directory error
                try:
                    mlflow.keras.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception as e:
                    print('  -> Primary keras log_model failed:', e)
                    saved_path = os.path.join(tmp_path, 'model.keras')
                    os.makedirs(saved_path, exist_ok = True)
                    try:
                        model.save(saved_path, include_optimizer = True)
                    except Exception:
                        model.save(saved_path)
                    mlflow.log_artifact(saved_path, artifact_path = artifact_name)
                    return True

            elif fw == 'xgboost':
                inner = extract_xgb_from_pipeline(model) if isinstance(model, Pipeline) else None
                candidate = inner or model
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.xgboost.log_model(xgb_model=candidate, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                try:
                    if isinstance(candidate, xgb.core.Booster):
                        p = os.path.join(tmp_path, 'booster.json')
                        candidate.save_model(p)
                        mlflow.log_artifact(p, artifact_path = artifact_name)
                        return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

            else:
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.sklearn.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

        except Exception as e:
            print(f'mlflow_log_model_auto: primary path exception: {e}')
            return False

# Unified prediction/proba extractor (works for pipelines, sklearn, keras, xgboost)
def get_predictions_and_probas(model, framework, X_eval_df, label_encoder):
    if framework == 'keras':
        y_pred_proba = model.predict(X_eval_df, verbose = 0)
        if y_pred_proba.ndim == 2 and y_pred_proba.shape[1] == 1:
            y_pred = (y_pred_proba.ravel() >= 0.5).astype(int)
            y_proba = y_pred_proba.ravel()
        else:
            y_pred = np.argmax(y_pred_proba, axis=1)
            y_proba = y_pred_proba
        return y_pred, y_proba

    if framework == 'xgboost':
        try:
            if hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_eval_df)
                if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                    y_pred = np.argmax(y_proba, axis = 1)
                    y_proba_for_auc = y_proba
                else:
                    y_pred = (y_proba.ravel() > 0.5).astype(int)
                    y_proba_for_auc = y_proba.ravel()
                return y_pred, y_proba_for_auc

            if isinstance(model, xgb.core.Booster):
                dmat = xgb.DMatrix(X_eval_df)
                probs = model.predict(dmat)
                if probs.ndim == 1:
                    y_pred = (probs > 0.5).astype(int)
                    return y_pred, probs.ravel()
                else:
                    y_pred = np.argmax(probs, axis=1)
                    return y_pred, probs
        except Exception:
            pass

        y_pred_raw = model.predict(X_eval_df)
        if isinstance(y_pred_raw[0], str):
            y_pred = label_encoder.transform(y_pred_raw)
        else:
            y_pred = np.asarray(y_pred_raw).astype(int)
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                return y_pred, y_proba
            else:
                return y_pred, y_proba.ravel()
        except Exception:
            return y_pred, None

    y_pred_raw = model.predict(X_eval_df)
    if isinstance(y_pred_raw[0], str):
        y_pred = label_encoder.transform(y_pred_raw)
    else:
        y_pred = np.asarray(y_pred_raw).astype(int)

    y_proba_for_auc = None
    if hasattr(model, 'predict_proba'):
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                y_proba_for_auc = y_proba
            else:
                y_proba_for_auc = y_proba.ravel()
        except Exception:
            y_proba_for_auc = None
    elif hasattr(model, 'decision_function'):
        try:
            dec = model.decision_function(X_eval_df)
            dec = np.ravel(dec)
            if dec.max() != dec.min():
                y_proba_for_auc = (dec - dec.min()) / (dec.max() - dec.min())
            else:
                y_proba_for_auc = dec
        except Exception:
            y_proba_for_auc = None

    return y_pred, y_proba_for_auc

# Main loop
f1_average = 'macro'
predictions_dict = {}

for model_name, path, framework, data_type, used_smote in models_to_log:
    print('\n' + '=' * 70)
    print(f'Loading {model_name}...')

    model = None
    xgb_params_loaded = None
    try:
        if framework == 'keras':
            model = keras.models.load_model(path)
        elif framework == 'xgboost':
            try:
                model = joblib.load(path)
            except Exception:
                try:
                    clf = xgb.XGBClassifier()
                    clf.load_model(path)
                    model = clf
                except Exception:
                    try:
                        booster = xgb.Booster()
                        booster.load_model(path)
                        model = booster
                    except Exception as e:
                        raise e
            params_path = path.replace('.json', '_params.json')
            if os.path.exists(params_path):
                try:
                    with open(params_path, 'r') as f:
                        xgb_params_loaded = json.load(f)
                except Exception:
                    xgb_params_loaded = None
        else:
            model = joblib.load(path)
    except Exception as e:
        print(f'Error loading {model_name}: {e}')
        continue

    if model_name == 'Stacking Classifier':
        X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
        reason = "Stacking Classifier: Using original 'X_test' (trained that way)"
    else:
        if framework != 'keras' and model_includes_scaler(model):
            X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
            reason = "Pipeline includes scaler: Using original 'X_test' (pipeline will scale)"
        else:
            X_eval = X_test_scaled if data_type == 'scaled' else X_test
            X_eval_df = ensure_dataframe(X_eval, ref_columns = X_train.columns)
            reason = f"Data type = '{data_type}': Using '{'X_test_scaled' if data_type == 'scaled' else 'X_test'}'"

    print('  ->', reason)

    try:
        y_pred, y_proba_for_auc = get_predictions_and_probas(model, framework, X_eval_df, label_encoder)
    except Exception as e:
        print(f'Prediction failed for {model_name}: {e}')
        continue

    y_true_enc = Y_test_encoded
    acc = accuracy_score(y_true_enc, y_pred)
    f1 = f1_score(y_true_enc, y_pred, average = f1_average)

    auc_val = None
    try:
        n_classes = len(np.unique(y_true_enc))
        if n_classes == 2 and y_proba_for_auc is not None:
            if y_proba_for_auc.ndim == 2 and y_proba_for_auc.shape[1] == 2:
                auc_val = roc_auc_score(y_true_enc, y_proba_for_auc[:, 1])
            else:
                auc_val = roc_auc_score(y_true_enc, y_proba_for_auc)
        else:
            # No ROC AUC for multiclass
            auc_val = None
    except Exception as e:
        print(f"  -> Warning: roc_auc_score failed: {e}; y_proba shape: {np.shape(y_proba_for_auc) if y_proba_for_auc is not None else 'None'}")
        auc_val = None

    print(f"  -> Accuracy: {acc:.4f}, F1 ({f1_average}): {f1:.4f}, ROC AUC: {auc_val if auc_val is not None else 'None'}")
    print('  -> Sample preds (first 10):', list(y_pred[:10]))
    unique, counts = np.unique(y_pred, return_counts = True)
    print('  -> Unique pred counts:', dict(zip(unique.tolist(), counts.tolist())))

    predictions_dict[model_name] = y_pred

    run_name = f'{model_name} Multiclass (Charging State)'
    with mlflow.start_run(run_name = run_name) as run:
        row = df_prod[df_prod['Model'] == model_name]
        if not row.empty:
            mlflow.log_metric('Prediction Time secs', float(row['Prediction Time (sec)'].iloc[0]))
          # mlflow.log_metric('Memory Used (kB)', float(row['Memory Used (kB)'].iloc[0]))
            mlflow.log_metric('CPU Time secs', float(row['CPU Time (sec)'].iloc[0]))
            mlflow.log_metric('Physical Cores', int(row['Physical Cores'].iloc[0]))
            mlflow.log_metric('Logical Cores', int(row['Logical Cores'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Raw', float(row['CPU % Used (Raw)'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Normalized', float(row['CPU % Used (Normalized)'].iloc[0]))
            mlflow.log_metric('Model Size MB', float(row['Model Size (MB)'].iloc[0]))
          # mlflow.log_metric('F1 Macro (CSV)', float(row['F1 Macro'])) # I log it from the model not the csv

        mlflow.log_metric('Accuracy', float(f'{acc:.4f}'))
        mlflow.log_metric('F1 macro', float(f'{f1:.4f}'))
        if auc_val is not None:
            mlflow.log_metric('ROC AUC', float(f'{auc_val:.4f}'))

        mlflow.log_param('SMOTE', bool(used_smote))
        mlflow.set_tag('SMOTE', str(bool(used_smote)))
        mlflow.log_param('Framework', framework)
        mlflow.log_param('ModelPath', path)

        try:
            if framework == 'keras':
                kp = keras_params_summary(model)
                safe_kp = _safe_params_dict(kp, prefix = 'keras_')
                if safe_kp:
                    mlflow.log_params(safe_kp)

            elif framework == 'xgboost':
                if isinstance(model, Pipeline):
                    inner = extract_xgb_from_pipeline(model)
                    if inner:
                        try:
                            safe = safe_log_params_iter(inner, prefix = 'xgb_')
                            if safe:
                                mlflow.log_params(safe)
                        except Exception:
                            pass
                else:
                    try:
                        if hasattr(model, 'get_xgb_params'):
                            xp = model.get_xgb_params()
                            mlflow.log_params(_safe_params_dict(xp, prefix = 'xgb_'))
                    except Exception:
                        pass
                    try:
                        if hasattr(model, 'get_params'):
                            gp = model.get_params()
                            safe_gp = _safe_params_dict(gp, prefix = 'xgb_')
                            if safe_gp:
                                mlflow.log_params(safe_gp)
                    except Exception:
                        pass
                    if xgb_params_loaded:
                        mlflow.log_params(_safe_params_dict(xgb_params_loaded, prefix = 'xgb_file_'))

            elif 'stack' in model_name.lower() or hasattr(model, 'final_estimator_'):
                try:
                    if hasattr(model, 'final_estimator_'):
                        try:
                            meta_params = safe_log_params_iter(model.final_estimator_, prefix = 'meta_')
                            if meta_params:
                                mlflow.log_params(meta_params)
                        except Exception:
                            pass
                    if hasattr(model, 'named_estimators_'):
                        for name, est in model.named_estimators_.items():
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{name}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                    elif hasattr(model, 'estimators_'):
                        for i, est in enumerate(model.estimators_):
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{i}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                except Exception as e:
                    print('  -> Warning logging stacking params:', e)

            else:
                if hasattr(model, 'get_params'):
                    try:
                        gp = model.get_params()
                        mlflow.log_params(_safe_params_dict(gp))
                    except Exception:
                        if isinstance(model, Pipeline):
                            for name, step in model.named_steps.items():
                                if hasattr(step, 'get_params'):
                                    mlflow.log_params(_safe_params_dict(step.get_params(), prefix = f'{name}__'))
        except Exception as e:
            print('  -> Warning while preparing params to log:', e)

        try:
            target_names = label_encoder.classes_ if 'label_encoder' in globals() else None
            creport_dict = classification_report(y_true_enc, y_pred, output_dict = True)
            creport_text = classification_report(y_true_enc, y_pred, target_names = target_names)
            mlflow.log_text(json.dumps(creport_dict, indent = 4), 'classification_report.json')
            mlflow.log_text(creport_text, 'classification_report.txt')
        except Exception as e:
            print('  -> Warning logging classification report:', e)

        try:
            logged_ok = mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = X_eval_df)
            if not logged_ok:
                print('  -> Warning: model artifact not logged via standard mlflow path and fallback.')
        except Exception as e:
            print('  -> Error logging model artifact:', e)

        try:
            run_id = run.info.run_id
            exp_id = run.info.experiment_id
            print(f'  -> MLflow run id: {run_id} (experiment {exp_id})')
        except Exception:
            pass

    print(f'✅ Logged {model_name} (SMOTE = {used_smote})')


# After loop: cross-model identical prediction check
print('\n' + '=' * 70)
print('Cross-model prediction overlap:')
names = list(predictions_dict.keys())
for i in range(len(names)):
    for j in range(i+1, len(names)):
        a, b = names[i], names[j]
        overlap = np.mean(predictions_dict[a] == predictions_dict[b])
        print(f'  - {a} vs {b}: identical fraction = {overlap:.3f}')

======================================================================
Loading KNN...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8260, F1 (macro): 0.8077, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 3037, 1: 1112, 2: 1770}
  -> MLflow run id: 9441b85cc72f4a26a21fb246c3910faf (experiment 1)
🏃 View run KNN Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/9441b85cc72f4a26a21fb246c3910faf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged KNN (SMOTE = False)

======================================================================
Loading KNN SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8081, F1 (macro): 0.8049, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 1, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2517, 1: 1622, 2: 1780}
  -> MLflow run id: 86f09a3895aa4207ab3b787300511df6 (experiment 1)
🏃 View run KNN SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/86f09a3895aa4207ab3b787300511df6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged KNN SMOTE (SMOTE = True)

======================================================================
Loading RBF SVM...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8108, F1 (macro): 0.7853, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 1, 2, 2]
  -> Unique pred counts: {0: 3145, 1: 1006, 2: 1768}
  -> MLflow run id: 5154ba66f9f5432fb0e125b6c3b4091f (experiment 1)
🏃 View run RBF SVM Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/5154ba66f9f5432fb0e125b6c3b4091f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged RBF SVM (SMOTE = False)

======================================================================
Loading RBF SVM SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7687, F1 (macro): 0.7750, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 1, 0, 1, 2, 2]
  -> Unique pred counts: {0: 2086, 1: 2061, 2: 1772}
  -> MLflow run id: 1d4f132df29549cd9254f75149d2fdce (experiment 1)
🏃 View run RBF SVM SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/1d4f132df29549cd9254f75149d2fdce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged RBF SVM SMOTE (SMOTE = True)

======================================================================
Loading XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8571, F1 (macro): 0.8422, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 3051, 1: 1112, 2: 1756}
  -> MLflow run id: cd221c2c5af746a99feff1c8956f7f2e (experiment 1)
🏃 View run XGBoost Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/cd221c2c5af746a99feff1c8956f7f2e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged XGBoost (SMOTE = False)

======================================================================
Loading XGBoost SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8510, F1 (macro): 0.8462, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2667, 1: 1495, 2: 1757}
  -> MLflow run id: b363aae952f84217ba4a1c40ff81417e (experiment 1)
🏃 View run XGBoost SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/b363aae952f84217ba4a1c40ff81417e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged XGBoost SMOTE (SMOTE = True)

======================================================================
Loading Logistic Regression...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7420, F1 (macro): 0.7501, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 1, 0, 2, 2]
  -> Unique pred counts: {0: 1976, 1: 2147, 2: 1796}
  -> MLflow run id: 8c6b1ff4607b4c7192df8e043bf7c8de (experiment 1)
🏃 View run Logistic Regression Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/8c6b1ff4607b4c7192df8e043bf7c8de
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged Logistic Regression (SMOTE = False)

======================================================================
Loading Logistic Regression SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7425, F1 (macro): 0.7505, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 1, 0, 2, 2]
  -> Unique pred counts: {0: 1985, 1: 2139, 2: 1795}
  -> MLflow run id: c41ce823bca04421a7eeeee04a031523 (experiment 1)
🏃 View run Logistic Regression SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/c41ce823bca04421a7eeeee04a031523
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged Logistic Regression SMOTE (SMOTE = True)

======================================================================
Loading Random Forest...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.8493, F1 (macro): 0.8397, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2855, 1: 1309, 2: 1755}
  -> MLflow run id: 4914ec8f7ee94f19b88c7e05a3d74bc1 (experiment 1)
🏃 View run Random Forest Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/4914ec8f7ee94f19b88c7e05a3d74bc1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged Random Forest (SMOTE = False)

======================================================================
Loading Random Forest SMOTE...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.8495, F1 (macro): 0.8400, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2856, 1: 1312, 2: 1751}
  -> MLflow run id: cdf490a13f214a10ad7cc0b5701bc7a1 (experiment 1)
🏃 View run Random Forest SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/cdf490a13f214a10ad7cc0b5701bc7a1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged Random Forest SMOTE (SMOTE = True)

======================================================================
Loading ANN...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8033, F1 (macro): 0.7771, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 3141, 1: 1022, 2: 1756}
  -> MLflow run id: 1a36e71376af4641ac30cfa2c367ee18 (experiment 1)
🏃 View run ANN Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/1a36e71376af4641ac30cfa2c367ee18
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged ANN (SMOTE = False)

======================================================================
Loading ANN SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.7652, F1 (macro): 0.7688, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2237, 1: 1915, 2: 1767}
  -> MLflow run id: c04597c0b28b494794fc5e0cc4fe9ad3 (experiment 1)
🏃 View run ANN SMOTE Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/c04597c0b28b494794fc5e0cc4fe9ad3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged ANN SMOTE (SMOTE = True)

======================================================================
Loading Stacking Classifier...
  -> Stacking Classifier: Using original 'X_test' (trained that way)
  -> Accuracy: 0.8539, F1 (macro): 0.8439, ROC AUC: None
  -> Sample preds (first 10): [0, 0, 1, 0, 0, 0, 0, 0, 2, 2]
  -> Unique pred counts: {0: 2874, 1: 1285, 2: 1760}
  -> MLflow run id: 90f731516b434ba5acb79f1fec9bf8bb (experiment 1)
🏃 View run Stacking Classifier Multiclass (Charging State) at: http://127.0.0.1:5000/#/experiments/1/runs/90f731516b434ba5acb79f1fec9bf8bb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Logged Stacking Classifier (SMOTE = False)

======================================================================
Cross-model prediction overlap:
  - KNN vs KNN SMOTE: identical fraction = 0.912
  - KNN vs RBF SVM: identical fraction = 0.881
  - KNN vs RBF SVM SMOTE: identical fraction = 0.811
  - KNN vs XGBoost: identical fraction = 0.908
  - KNN vs XGBoost SMOTE: identical fraction = 0.885
  - KNN vs Logistic Regression: identical fraction = 0.775
  - KNN vs Logistic Regression SMOTE: identical fraction = 0.776
  - KNN vs Random Forest: identical fraction = 0.907
  - KNN vs Random Forest SMOTE: identical fraction = 0.911
  - KNN vs ANN: identical fraction = 0.870
  - KNN vs ANN SMOTE: identical fraction = 0.810
  - KNN vs Stacking Classifier: identical fraction = 0.917
  - KNN SMOTE vs RBF SVM: identical fraction = 0.829
  - KNN SMOTE vs RBF SVM SMOTE: identical fraction = 0.829
  - KNN SMOTE vs XGBoost: identical fraction = 0.868
  - KNN SMOTE vs XGBoost SMOTE: identical fraction = 0.879
  - KNN SMOTE vs Logistic Regression: identical fraction = 0.795
  - KNN SMOTE vs Logistic Regression SMOTE: identical fraction = 0.796
  - KNN SMOTE vs Random Forest: identical fraction = 0.885
  - KNN SMOTE vs Random Forest SMOTE: identical fraction = 0.891
  - KNN SMOTE vs ANN: identical fraction = 0.819
  - KNN SMOTE vs ANN SMOTE: identical fraction = 0.811
  - KNN SMOTE vs Stacking Classifier: identical fraction = 0.893
  - RBF SVM vs RBF SVM SMOTE: identical fraction = 0.821
  - RBF SVM vs XGBoost: identical fraction = 0.883
  - RBF SVM vs XGBoost SMOTE: identical fraction = 0.848
  - RBF SVM vs Logistic Regression: identical fraction = 0.785
  - RBF SVM vs Logistic Regression SMOTE: identical fraction = 0.786
  - RBF SVM vs Random Forest: identical fraction = 0.861
  - RBF SVM vs Random Forest SMOTE: identical fraction = 0.863
  - RBF SVM vs ANN: identical fraction = 0.955
  - RBF SVM vs ANN SMOTE: identical fraction = 0.836
  - RBF SVM vs Stacking Classifier: identical fraction = 0.867
  - RBF SVM SMOTE vs XGBoost: identical fraction = 0.814
  - RBF SVM SMOTE vs XGBoost SMOTE: identical fraction = 0.837
  - RBF SVM SMOTE vs Logistic Regression: identical fraction = 0.907
  - RBF SVM SMOTE vs Logistic Regression SMOTE: identical fraction = 0.908
  - RBF SVM SMOTE vs Random Forest: identical fraction = 0.824
  - RBF SVM SMOTE vs Random Forest SMOTE: identical fraction = 0.825
  - RBF SVM SMOTE vs ANN: identical fraction = 0.819
  - RBF SVM SMOTE vs ANN SMOTE: identical fraction = 0.932
  - RBF SVM SMOTE vs Stacking Classifier: identical fraction = 0.828
  - XGBoost vs XGBoost SMOTE: identical fraction = 0.929
  - XGBoost vs Logistic Regression: identical fraction = 0.780
  - XGBoost vs Logistic Regression SMOTE: identical fraction = 0.780
  - XGBoost vs Random Forest: identical fraction = 0.946
  - XGBoost vs Random Forest SMOTE: identical fraction = 0.939
  - XGBoost vs ANN: identical fraction = 0.876
  - XGBoost vs ANN SMOTE: identical fraction = 0.815
  - XGBoost vs Stacking Classifier: identical fraction = 0.960
  - XGBoost SMOTE vs Logistic Regression: identical fraction = 0.804
  - XGBoost SMOTE vs Logistic Regression SMOTE: identical fraction = 0.805
  - XGBoost SMOTE vs Random Forest: identical fraction = 0.943
  - XGBoost SMOTE vs Random Forest SMOTE: identical fraction = 0.937
  - XGBoost SMOTE vs ANN: identical fraction = 0.837
  - XGBoost SMOTE vs ANN SMOTE: identical fraction = 0.829
  - XGBoost SMOTE vs Stacking Classifier: identical fraction = 0.949
  - Logistic Regression vs Logistic Regression SMOTE: identical fraction = 0.998
  - Logistic Regression vs Random Forest: identical fraction = 0.788
  - Logistic Regression vs Random Forest SMOTE: identical fraction = 0.787
  - Logistic Regression vs ANN: identical fraction = 0.786
  - Logistic Regression vs ANN SMOTE: identical fraction = 0.919
  - Logistic Regression vs Stacking Classifier: identical fraction = 0.788
  - Logistic Regression SMOTE vs Random Forest: identical fraction = 0.788
  - Logistic Regression SMOTE vs Random Forest SMOTE: identical fraction = 0.788
  - Logistic Regression SMOTE vs ANN: identical fraction = 0.787
  - Logistic Regression SMOTE vs ANN SMOTE: identical fraction = 0.920
  - Logistic Regression SMOTE vs Stacking Classifier: identical fraction = 0.789
  - Random Forest vs Random Forest SMOTE: identical fraction = 0.971
  - Random Forest vs ANN: identical fraction = 0.853
  - Random Forest vs ANN SMOTE: identical fraction = 0.819
  - Random Forest vs Stacking Classifier: identical fraction = 0.976
  - Random Forest SMOTE vs ANN: identical fraction = 0.851
  - Random Forest SMOTE vs ANN SMOTE: identical fraction = 0.819
  - Random Forest SMOTE vs Stacking Classifier: identical fraction = 0.964
  - ANN vs ANN SMOTE: identical fraction = 0.846
  - ANN vs Stacking Classifier: identical fraction = 0.860
  - ANN SMOTE vs Stacking Classifier: identical fraction = 0.822

# Multiclass Classification (Both States)

In [16]:
# Set the experiment in MLflow
mlflow.set_experiment('Multiclass Classification (Both States)')

<Experiment: artifact_location='/Users/yannis/mlflow-artifacts/2', creation_time=1761295858748, experiment_id='2', last_update_time=1761297936105, lifecycle_stage='active', name='Multiclass Classification (Both States)', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [17]:
# Load the sheet into a DataFrame
df = pd.read_csv(DATA_PATH)

# Display basic info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115298 entries, 0 to 115297
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           115298 non-null  object
 1   shunt_voltage  115298 non-null  int64
 2   bus_voltage_V  115298 non-null  float64
 3   current_mA     115298 non-null  int64
 4   power_mW       115298 non-null  int64
 5   State          115298 non-null  object
 6   Attack         115298 non-null  object
 7   Attack-Group   115298 non-null  object
 8   Label          115298 non-null  object
 9   interface      115298 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 8.8+ MB

In [18]:
# Print the first rows of the DataFrame
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp

In [19]:
# Define mapping dictionary
attack_mapping = {
    'syn-flood': 'DoS',
    'tcp-flood': 'DoS',
    'cryptojacking': 'Cryptojacking',
    'vuln-scan': 'Recon',
    'syn-stealth': 'Recon',
    'Backdoor': 'Backdoor',
    'none': 'Benign'
}

# Apply mapping to create 'Attack-New' column
df['Attack-New'] = df['Attack'].map(attack_mapping)

# Print the first rows of the DataFrame to verify the new column
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp,DoS
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp,DoS
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp,DoS
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp,DoS
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp,DoS

In [20]:
# Select numerical features for classification (excluding categorical columns)
numerical_features = ['shunt_voltage', 'bus_voltage_V', 'current_mA', 'power_mW']

# Define features (X) and target variable (Y)
X = df[numerical_features]
Y = df['Attack-New']

In [21]:
# Split the dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y, shuffle = True)

In [22]:
# Split the training set into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.2, random_state = 42, stratify = Y_train, shuffle = True)

In [23]:
# Set the encoder
label_encoder = LabelEncoder()

# Encode 'Attack-New' labels as numbers for each subset
# Note: This is done after splitting to avoid data leakage
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_val_encoded = label_encoder.transform(Y_val)
Y_test_encoded = label_encoder.transform(Y_test)

# Check what each number represents
print('Label encoder classes:', label_encoder.classes_)

Label encoder classes: ['Backdoor' 'Benign' 'Cryptojacking' 'DoS' 'Recon']

In [24]:
# Create the scaler
scaler = StandardScaler()

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Shape of the scaled data
print(f'Shape of X_train_scaled: {X_train_scaled.shape}')
print(f'Shape of X_val_scaled: {X_val_scaled.shape}')
print(f'Shape of X_test_scaled: {X_test_scaled.shape}')

Shape of X_train_scaled: (73790, 4)
Shape of X_val_scaled: (18448, 4)
Shape of X_test_scaled: (23060, 4)

In [ ]:
# Suppress specific warnings for cleaner output
warnings.filterwarnings('ignore', category = UserWarning)

# Models list
models_to_log = [
    ('KNN', MODELS_DIR + 'knn_multi_both_best_model.pkl', 'sklearn', 'scaled', False),
    ('KNN SMOTE', MODELS_DIR + 'knn_multi_both_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('XGBoost', MODELS_DIR + 'xgboost_multi_both_best_model.json', 'xgboost', 'scaled', False),
    ('XGBoost SMOTE', MODELS_DIR + 'xgboost_multi_both_smote_best_model.json', 'xgboost', 'scaled', True),
    ('Logistic Regression', MODELS_DIR + 'logistic_regression_multi_both_best_model.pkl', 'sklearn', 'scaled', False),
    ('Logistic Regression SMOTE', MODELS_DIR + 'logistic_regression_multi_both_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('Random Forest', MODELS_DIR + 'random_forest_multi_both_best_model.pkl', 'sklearn', 'original', False),
    ('Random Forest SMOTE', MODELS_DIR + 'random_forest_multi_both_smote_best_model.pkl', 'sklearn', 'original', True),
    ('ANN', MODELS_DIR + 'ann_multi_both_model.keras', 'keras', 'scaled', False),
    ('ANN SMOTE', MODELS_DIR + 'ann_multi_both_smote_model.keras', 'keras', 'scaled', True),
    ('Stacking Classifier', MODELS_DIR + 'stacking_clf_multi_both_best_model.pkl', 'sklearn', 'original', False),
]

# Load production results CSV
# Clean CSV columns for MLflow logging
df_prod = pd.read_csv('df_production_results_multi_both.csv')

# Ensure numeric
for col in ['Prediction Time (sec)','F1 Macro', 'Memory Used (kB)', 'CPU Time (sec)', 'Physical Cores', 'Logical Cores', 'CPU % Used (Raw)',
            'CPU % Used (Normalized)','Model Size (MB)']:
    df_prod[col] = pd.to_numeric(df_prod[col], errors = 'coerce')

# Sanity checks
required_globals = ['X_train', 'X_test', 'X_test_scaled', 'Y_test_encoded', 'label_encoder']
missing = [g for g in required_globals if g not in globals()]
if missing:
    raise RuntimeError(f'Please ensure these globals exist before running: {missing}')

# Helper functions
def ensure_dataframe(X, ref_columns):
    if isinstance(X, np.ndarray):
        return pd.DataFrame(X, columns = list(ref_columns))
    if isinstance(X, pd.DataFrame):
        if list(X.columns) != list(ref_columns) and X.shape[1] == len(ref_columns):
            return pd.DataFrame(X.values, columns = list(ref_columns))
        return X
    raise ValueError('X must be numpy array or pandas DataFrame')

def model_includes_scaler(model):
    if isinstance(model, Pipeline):
        for step in model.named_steps.values():
            cls_name = step.__class__.__name__.lower()
            if 'scaler' in cls_name or 'standardscaler' in cls_name or 'minmax' in cls_name or 'preprocessor' in cls_name:
                return True
    return False

def _safe_params_dict(params: dict, prefix = ''):
    safe = {}
    for k, v in params.items():
        key = f'{prefix}{k}'
        if isinstance(v, (str, int, float, bool)) or v is None:
            safe[key] = v
        else:
            try:
                s = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
                safe[key] = s[:200]
            except Exception:
                safe[key] = str(type(v))
    return safe

def keras_params_summary(model: keras.Model):
    params = {}
    try:
        params['keras_total_params'] = model.count_params()
    except Exception:
        params['keras_total_params'] = None
    params['keras_layers_count'] = len(model.layers)
    for i, layer in enumerate(model.layers):
        try:
            cfg = layer.get_config()
        except Exception:
            cfg = {}
        params[f'layer_{i}_class'] = layer.__class__.__name__
        if 'units' in cfg:
            params[f'layer_{i}_units'] = cfg.get('units')
        if 'activation' in cfg:
            params[f'layer_{i}_activation'] = cfg.get('activation')
    try:
        opt = model.optimizer.get_config()
        params['optimizer'] = model.optimizer.__class__.__name__
        for k, v in opt.items():
            params[f'opt_{k}'] = v if isinstance(v, (str, int, float, bool)) else str(v)
    except Exception:
        pass
    try:
        params['loss'] = model.loss if not callable(model.loss) else str(model.loss)
    except Exception:
        pass
    return params

def extract_xgb_from_pipeline(m):
    if not isinstance(m, Pipeline):
        return None
    for step in m.named_steps.values():
        cls = step.__class__.__name__.lower()
        if 'xgb' in cls or hasattr(step, 'get_xgb_params'):
            return step
    return None

def safe_head_example(X, n=8):
    try:
        if isinstance(X, pd.DataFrame):
            return X.head(n)
        if isinstance(X, np.ndarray):
            return pd.DataFrame(X[:n], columns = X_train.columns)
    except Exception:
        pass
    return None

def safe_predict_for_signature(model, X_example, framework):
    try:
        fw = (framework or '').lower()
        if fw == 'keras':
            preds = model.predict(X_example, verbose = 0)
            return preds
        elif fw == 'xgboost':
            if isinstance(model, xgb.core.Booster):
                d = xgb.DMatrix(X_example)
                preds = model.predict(d)
                return preds
            else:
                if hasattr(model, 'predict'):
                    return model.predict(X_example)
        else:
            return model.predict(X_example)
    except Exception:
        return None

def safe_log_params_iter(obj, prefix = ''):
    safe = {}
    try:
        gp = obj.get_params()
        for k, v in gp.items():
            try:
                if isinstance(v, (list, dict)):
                    safe[f'{prefix}{k}'] = json.dumps(v)[:400]
                elif hasattr(v, '__name__') and getattr(v, '__name__'):
                    safe[f'{prefix}{k}'] = getattr(v, '__name__')
                else:
                    safe[f'{prefix}{k}'] = v
            except Exception:
                safe[f'{prefix}{k}'] = str(type(v))
    except Exception:
        pass
    return safe

def mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = None):
    fw = (framework or '').lower()
    example_df = safe_head_example(X_example) if X_example is not None else None

    input_example_np = None
    signature = None
    input_example = None

    if example_df is not None:
        input_example_np = example_df.values if isinstance(example_df, pd.DataFrame) else example_df
        input_example = input_example_np
        preds = safe_predict_for_signature(model, input_example_np, fw)
        try:
            signature = infer_signature(input_example_np, preds) if preds is not None else infer_signature(input_example_np, None)
        except Exception:
            signature = None

    with tempfile.TemporaryDirectory(prefix = 'mlflow_model_') as tmp_path:
        try:
            if fw == 'keras':
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                # Skip passing input_example here to avoid MLflow directory error
                try:
                    mlflow.keras.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception as e:
                    print('  -> Primary keras log_model failed:', e)
                    saved_path = os.path.join(tmp_path, 'model.keras')
                    os.makedirs(saved_path, exist_ok = True)
                    try:
                        model.save(saved_path, include_optimizer = True)
                    except Exception:
                        model.save(saved_path)
                    mlflow.log_artifact(saved_path, artifact_path = artifact_name)
                    return True

            elif fw == 'xgboost':
                inner = extract_xgb_from_pipeline(model) if isinstance(model, Pipeline) else None
                candidate = inner or model
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.xgboost.log_model(xgb_model = candidate, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                try:
                    if isinstance(candidate, xgb.core.Booster):
                        p = os.path.join(tmp_path, 'booster.json')
                        candidate.save_model(p)
                        mlflow.log_artifact(p, artifact_path = artifact_name)
                        return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

            else:
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.sklearn.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

        except Exception as e:
            print(f'mlflow_log_model_auto: primary path exception: {e}')
            return False

# Unified prediction/proba extractor (works for pipelines, sklearn, keras, xgboost)
def get_predictions_and_probas(model, framework, X_eval_df, label_encoder):
    if framework == 'keras':
        y_pred_proba = model.predict(X_eval_df, verbose = 0)
        if y_pred_proba.ndim == 2 and y_pred_proba.shape[1] == 1:
            y_pred = (y_pred_proba.ravel() >= 0.5).astype(int)
            y_proba = y_pred_proba.ravel()
        else:
            y_pred = np.argmax(y_pred_proba, axis=1)
            y_proba = y_pred_proba
        return y_pred, y_proba

    if framework == 'xgboost':
        try:
            if hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_eval_df)
                if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                    y_pred = np.argmax(y_proba, axis=1)
                    y_proba_for_auc = y_proba
                else:
                    y_pred = (y_proba.ravel() > 0.5).astype(int)
                    y_proba_for_auc = y_proba.ravel()
                return y_pred, y_proba_for_auc

            if isinstance(model, xgb.core.Booster):
                dmat = xgb.DMatrix(X_eval_df)
                probs = model.predict(dmat)
                if probs.ndim == 1:
                    y_pred = (probs > 0.5).astype(int)
                    return y_pred, probs.ravel()
                else:
                    y_pred = np.argmax(probs, axis = 1)
                    return y_pred, probs
        except Exception:
            pass

        y_pred_raw = model.predict(X_eval_df)
        if isinstance(y_pred_raw[0], str):
            y_pred = label_encoder.transform(y_pred_raw)
        else:
            y_pred = np.asarray(y_pred_raw).astype(int)
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                return y_pred, y_proba
            else:
                return y_pred, y_proba.ravel()
        except Exception:
            return y_pred, None

    y_pred_raw = model.predict(X_eval_df)
    if isinstance(y_pred_raw[0], str):
        y_pred = label_encoder.transform(y_pred_raw)
    else:
        y_pred = np.asarray(y_pred_raw).astype(int)

    y_proba_for_auc = None
    if hasattr(model, 'predict_proba'):
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                y_proba_for_auc = y_proba
            else:
                y_proba_for_auc = y_proba.ravel()
        except Exception:
            y_proba_for_auc = None
    elif hasattr(model, 'decision_function'):
        try:
            dec = model.decision_function(X_eval_df)
            dec = np.ravel(dec)
            if dec.max() != dec.min():
                y_proba_for_auc = (dec - dec.min()) / (dec.max() - dec.min())
            else:
                y_proba_for_auc = dec
        except Exception:
            y_proba_for_auc = None

    return y_pred, y_proba_for_auc

# Main loop
f1_average = 'macro'
predictions_dict = {}

for model_name, path, framework, data_type, used_smote in models_to_log:
    print('\n' + '=' * 70)
    print(f'Loading {model_name}...')

    model = None
    xgb_params_loaded = None
    try:
        if framework == 'keras':
            model = keras.models.load_model(path)
        elif framework == 'xgboost':
            try:
                model = joblib.load(path)
            except Exception:
                try:
                    clf = xgb.XGBClassifier()
                    clf.load_model(path)
                    model = clf
                except Exception:
                    try:
                        booster = xgb.Booster()
                        booster.load_model(path)
                        model = booster
                    except Exception as e:
                        raise e
            params_path = path.replace('.json', '_params.json')
            if os.path.exists(params_path):
                try:
                    with open(params_path, 'r') as f:
                        xgb_params_loaded = json.load(f)
                except Exception:
                    xgb_params_loaded = None
        else:
            model = joblib.load(path)
    except Exception as e:
        print(f'Error loading {model_name}: {e}')
        continue

    if model_name == 'Stacking Classifier':
        X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
        reason = "Stacking Classifier: Using original 'X_test' (trained that way)"
    else:
        if framework != 'keras' and model_includes_scaler(model):
            X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
            reason = "Pipeline includes scaler: Using original 'X_test' (pipeline will scale)"
        else:
            X_eval = X_test_scaled if data_type == 'scaled' else X_test
            X_eval_df = ensure_dataframe(X_eval, ref_columns = X_train.columns)
            reason = f"Data type = '{data_type}': Using '{'X_test_scaled' if data_type == 'scaled' else 'X_test'}'"

    print('  ->', reason)

    try:
        y_pred, y_proba_for_auc = get_predictions_and_probas(model, framework, X_eval_df, label_encoder)
    except Exception as e:
        print(f'Prediction failed for {model_name}: {e}')
        continue

    y_true_enc = Y_test_encoded
    acc = accuracy_score(y_true_enc, y_pred)
    f1 = f1_score(y_true_enc, y_pred, average = f1_average)

    auc_val = None
    try:
        n_classes = len(np.unique(y_true_enc))
        if n_classes == 2 and y_proba_for_auc is not None:
            if y_proba_for_auc.ndim == 2 and y_proba_for_auc.shape[1] == 2:
                auc_val = roc_auc_score(y_true_enc, y_proba_for_auc[:, 1])
            else:
                auc_val = roc_auc_score(y_true_enc, y_proba_for_auc)
        else:
            # No ROC AUC for multiclass
            auc_val = None
    except Exception as e:
        print(f"  -> Warning: roc_auc_score failed: {e}; y_proba shape: {np.shape(y_proba_for_auc) if y_proba_for_auc is not None else 'None'}")
        auc_val = None

    print(f"  -> Accuracy: {acc:.4f}, F1 ({f1_average}): {f1:.4f}, ROC AUC: {auc_val if auc_val is not None else 'None'}")
    print('  -> Sample preds (first 10):', list(y_pred[:10]))
    unique, counts = np.unique(y_pred, return_counts = True)
    print('  -> Unique pred counts:', dict(zip(unique.tolist(), counts.tolist())))

    predictions_dict[model_name] = y_pred

    run_name = f'{model_name} Multiclass (Both States)'
    with mlflow.start_run(run_name = run_name) as run:
        row = df_prod[df_prod['Model'] == model_name]
        if not row.empty:
            mlflow.log_metric('Prediction Time secs', float(row['Prediction Time (sec)'].iloc[0]))
          # mlflow.log_metric('Memory Used (kB)', float(row['Memory Used (kB)'].iloc[0]))
            mlflow.log_metric('CPU Time secs', float(row['CPU Time (sec)'].iloc[0]))
            mlflow.log_metric('Physical Cores', int(row['Physical Cores'].iloc[0]))
            mlflow.log_metric('Logical Cores', int(row['Logical Cores'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Raw', float(row['CPU % Used (Raw)'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Normalized', float(row['CPU % Used (Normalized)'].iloc[0]))
            mlflow.log_metric('Model Size MB', float(row['Model Size (MB)'].iloc[0]))
          # mlflow.log_metric('F1 Macro (CSV)', float(row['F1 Macro'])) # I log it from the model not the csv
        
        mlflow.log_metric('Accuracy', float(f'{acc:.4f}'))
        mlflow.log_metric('F1 macro', float(f'{f1:.4f}'))
        if auc_val is not None:
            mlflow.log_metric('ROC AUC', float(f'{auc_val:.4f}'))

        mlflow.log_param('SMOTE', bool(used_smote))
        mlflow.set_tag('SMOTE', str(bool(used_smote)))
        mlflow.log_param('Framework', framework)
        mlflow.log_param('ModelPath', path)

        try:
            if framework == 'keras':
                kp = keras_params_summary(model)
                safe_kp = _safe_params_dict(kp, prefix = 'keras_')
                if safe_kp:
                    mlflow.log_params(safe_kp)

            elif framework == 'xgboost':
                if isinstance(model, Pipeline):
                    inner = extract_xgb_from_pipeline(model)
                    if inner:
                        try:
                            safe = safe_log_params_iter(inner, prefix = 'xgb_')
                            if safe:
                                mlflow.log_params(safe)
                        except Exception:
                            pass
                else:
                    try:
                        if hasattr(model, 'get_xgb_params'):
                            xp = model.get_xgb_params()
                            mlflow.log_params(_safe_params_dict(xp, prefix = 'xgb_'))
                    except Exception:
                        pass
                    try:
                        if hasattr(model, 'get_params'):
                            gp = model.get_params()
                            safe_gp = _safe_params_dict(gp, prefix = 'xgb_')
                            if safe_gp:
                                mlflow.log_params(safe_gp)
                    except Exception:
                        pass
                    if xgb_params_loaded:
                        mlflow.log_params(_safe_params_dict(xgb_params_loaded, prefix = 'xgb_file_'))

            elif 'stack' in model_name.lower() or hasattr(model, 'final_estimator_'):
                try:
                    if hasattr(model, 'final_estimator_'):
                        try:
                            meta_params = safe_log_params_iter(model.final_estimator_, prefix = 'meta_')
                            if meta_params:
                                mlflow.log_params(meta_params)
                        except Exception:
                            pass
                    if hasattr(model, 'named_estimators_'):
                        for name, est in model.named_estimators_.items():
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{name}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                    elif hasattr(model, 'estimators_'):
                        for i, est in enumerate(model.estimators_):
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{i}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                except Exception as e:
                    print('  -> Warning logging stacking params:', e)

            else:
                if hasattr(model, 'get_params'):
                    try:
                        gp = model.get_params()
                        mlflow.log_params(_safe_params_dict(gp))
                    except Exception:
                        if isinstance(model, Pipeline):
                            for name, step in model.named_steps.items():
                                if hasattr(step, 'get_params'):
                                    mlflow.log_params(_safe_params_dict(step.get_params(), prefix = f'{name}__'))
        except Exception as e:
            print('  -> Warning while preparing params to log:', e)

        try:
            target_names = label_encoder.classes_ if 'label_encoder' in globals() else None
            creport_dict = classification_report(y_true_enc, y_pred, output_dict = True)
            creport_text = classification_report(y_true_enc, y_pred, target_names = target_names)
            mlflow.log_text(json.dumps(creport_dict, indent = 4), 'classification_report.json')
            mlflow.log_text(creport_text, 'classification_report.txt')
        except Exception as e:
            print('  -> Warning logging classification report:', e)

        try:
            logged_ok = mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = X_eval_df)
            if not logged_ok:
                print('  -> Warning: model artifact not logged via standard mlflow path and fallback.')
        except Exception as e:
            print('  -> Error logging model artifact:', e)

        try:
            run_id = run.info.run_id
            exp_id = run.info.experiment_id
            print(f'  -> MLflow run id: {run_id} (experiment {exp_id})')
        except Exception:
            pass

    print(f'✅ Logged {model_name} (SMOTE = {used_smote})')


# After loop: cross-model identical prediction check
print('\n' + '=' * 70)
print('Cross-model prediction overlap:')
names = list(predictions_dict.keys())
for i in range(len(names)):
    for j in range(i+1, len(names)):
        a, b = names[i], names[j]
        overlap = np.mean(predictions_dict[a] == predictions_dict[b])
        print(f'  - {a} vs {b}: identical fraction = {overlap:.3f}')

======================================================================
Loading KNN...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.6110, F1 (macro): 0.6374, ROC AUC: None
  -> Sample preds (first 10): [3, 4, 1, 4, 1, 2, 3, 1, 1, 4]
  -> Unique pred counts: {0: 5099, 1: 2660, 2: 2426, 3: 5315, 4: 7560}
  -> MLflow run id: 5501649acaf74ac7adfccded721c3917 (experiment 2)
🏃 View run KNN Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/5501649acaf74ac7adfccded721c3917
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged KNN (SMOTE = False)

======================================================================
Loading KNN SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.5933, F1 (macro): 0.6170, ROC AUC: None
  -> Sample preds (first 10): [3, 4, 1, 4, 1, 2, 2, 1, 1, 4]
  -> Unique pred counts: {0: 4912, 1: 3229, 2: 3305, 3: 4395, 4: 7219}
  -> MLflow run id: 76e0f6de5e3d48bea16f340d722473cf (experiment 2)
🏃 View run KNN SMOTE Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/76e0f6de5e3d48bea16f340d722473cf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged KNN SMOTE (SMOTE = True)

======================================================================
Loading XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.6441, F1 (macro): 0.6551, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 4, 4, 1, 3, 3, 1, 1, 4]
  -> Unique pred counts: {0: 5022, 1: 2782, 2: 2299, 3: 3018, 4: 9939}
  -> MLflow run id: d795593f843840a6b5901c06a2401cdd (experiment 2)
🏃 View run XGBoost Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/d795593f843840a6b5901c06a2401cdd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged XGBoost (SMOTE = False)

======================================================================
Loading XGBoost SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.6325, F1 (macro): 0.6308, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 4, 4, 1, 2, 2, 1, 1, 4]
  -> Unique pred counts: {0: 5217, 1: 3218, 2: 3470, 3: 1584, 4: 9571}
  -> MLflow run id: 582049f975724212bedf71d91dcadb50 (experiment 2)
🏃 View run XGBoost SMOTE Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/582049f975724212bedf71d91dcadb50
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged XGBoost SMOTE (SMOTE = True)

======================================================================
Loading Logistic Regression...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.4555, F1 (macro): 0.4213, ROC AUC: None
  -> Sample preds (first 10): [4, 3, 1, 4, 4, 2, 2, 4, 4, 4]
  -> Unique pred counts: {0: 1870, 1: 2809, 2: 4783, 3: 2587, 4: 11011}
  -> MLflow run id: d45c2f84b0be4b8eacd6647866161df4 (experiment 2)
🏃 View run Logistic Regression Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/d45c2f84b0be4b8eacd6647866161df4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged Logistic Regression (SMOTE = False)

======================================================================
Loading Logistic Regression SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.4543, F1 (macro): 0.4206, ROC AUC: None
  -> Sample preds (first 10): [4, 3, 1, 4, 4, 2, 2, 4, 4, 4]
  -> Unique pred counts: {0: 1810, 1: 2939, 2: 4780, 3: 2595, 4: 10936}
  -> MLflow run id: 223647c55cc94d27814a9326988e1acb (experiment 2)
🏃 View run Logistic Regression SMOTE Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/223647c55cc94d27814a9326988e1acb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged Logistic Regression SMOTE (SMOTE = True)

======================================================================
Loading Random Forest...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.6311, F1 (macro): 0.6516, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 4, 4, 1, 2, 3, 1, 1, 4]
  -> Unique pred counts: {0: 4898, 1: 2778, 2: 2301, 3: 4210, 4: 8873}
  -> MLflow run id: 4745330a9589488895abad10eb2fa731 (experiment 2)
🏃 View run Random Forest Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/4745330a9589488895abad10eb2fa731
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged Random Forest (SMOTE = False)

======================================================================
Loading Random Forest SMOTE...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.6287, F1 (macro): 0.6457, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 4, 4, 1, 2, 2, 1, 1, 4]
  -> Unique pred counts: {0: 4975, 1: 3007, 2: 2792, 3: 3424, 4: 8862}
  -> MLflow run id: d85f192352734e518271dfb3ca73ffe4 (experiment 2)
🏃 View run Random Forest SMOTE Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/d85f192352734e518271dfb3ca73ffe4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged Random Forest SMOTE (SMOTE = True)

======================================================================
Loading ANN...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.6315, F1 (macro): 0.6358, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 3, 4, 1, 2, 3, 1, 1, 4]
  -> Unique pred counts: {0: 4869, 1: 2544, 2: 2385, 3: 2541, 4: 10721}
  -> MLflow run id: 5c1510bfc07d410ea7b67b3aaa819152 (experiment 2)
🏃 View run ANN Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/5c1510bfc07d410ea7b67b3aaa819152
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged ANN (SMOTE = False)

======================================================================
Loading ANN SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.6056, F1 (macro): 0.5949, ROC AUC: None
  -> Sample preds (first 10): [4, 0, 0, 4, 1, 2, 2, 1, 1, 4]
  -> Unique pred counts: {0: 5177, 1: 3000, 2: 3615, 3: 1130, 4: 10138}
  -> MLflow run id: 96a08ff193ce4e1ca119be1b09609e47 (experiment 2)
🏃 View run ANN SMOTE Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/96a08ff193ce4e1ca119be1b09609e47
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged ANN SMOTE (SMOTE = True)

======================================================================
Loading Stacking Classifier...
  -> Stacking Classifier: Using original 'X_test' (trained that way)
  -> Accuracy: 0.6432, F1 (macro): 0.6587, ROC AUC: None
  -> Sample preds (first 10): [4, 4, 4, 4, 1, 3, 3, 1, 1, 4]
  -> Unique pred counts: {0: 4695, 1: 2713, 2: 2290, 3: 3634, 4: 9728}
  -> MLflow run id: 4ba2622954d64fd9b1f3d593519ca762 (experiment 2)
🏃 View run Stacking Classifier Multiclass (Both States) at: http://127.0.0.1:5000/#/experiments/2/runs/4ba2622954d64fd9b1f3d593519ca762
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Logged Stacking Classifier (SMOTE = False)

======================================================================
Cross-model prediction overlap:
  - KNN vs KNN SMOTE: identical fraction = 0.849
  - KNN vs XGBoost: identical fraction = 0.789
  - KNN vs XGBoost SMOTE: identical fraction = 0.760
  - KNN vs Logistic Regression: identical fraction = 0.522
  - KNN vs Logistic Regression SMOTE: identical fraction = 0.519
  - KNN vs Random Forest: identical fraction = 0.827
  - KNN vs Random Forest SMOTE: identical fraction = 0.819
  - KNN vs ANN: identical fraction = 0.768
  - KNN vs ANN SMOTE: identical fraction = 0.735
  - KNN vs Stacking Classifier: identical fraction = 0.791
  - KNN SMOTE vs XGBoost: identical fraction = 0.748
  - KNN SMOTE vs XGBoost SMOTE: identical fraction = 0.771
  - KNN SMOTE vs Logistic Regression: identical fraction = 0.549
  - KNN SMOTE vs Logistic Regression SMOTE: identical fraction = 0.547
  - KNN SMOTE vs Random Forest: identical fraction = 0.787
  - KNN SMOTE vs Random Forest SMOTE: identical fraction = 0.804
  - KNN SMOTE vs ANN: identical fraction = 0.722
  - KNN SMOTE vs ANN SMOTE: identical fraction = 0.735
  - KNN SMOTE vs Stacking Classifier: identical fraction = 0.744
  - XGBoost vs XGBoost SMOTE: identical fraction = 0.895
  - XGBoost vs Logistic Regression: identical fraction = 0.611
  - XGBoost vs Logistic Regression SMOTE: identical fraction = 0.607
  - XGBoost vs Random Forest: identical fraction = 0.875
  - XGBoost vs Random Forest SMOTE: identical fraction = 0.869
  - XGBoost vs ANN: identical fraction = 0.889
  - XGBoost vs ANN SMOTE: identical fraction = 0.831
  - XGBoost vs Stacking Classifier: identical fraction = 0.945
  - XGBoost SMOTE vs Logistic Regression: identical fraction = 0.660
  - XGBoost SMOTE vs Logistic Regression SMOTE: identical fraction = 0.657
  - XGBoost SMOTE vs Random Forest: identical fraction = 0.832
  - XGBoost SMOTE vs Random Forest SMOTE: identical fraction = 0.863
  - XGBoost SMOTE vs ANN: identical fraction = 0.842
  - XGBoost SMOTE vs ANN SMOTE: identical fraction = 0.874
  - XGBoost SMOTE vs Stacking Classifier: identical fraction = 0.874
  - Logistic Regression vs Logistic Regression SMOTE: identical fraction = 0.990
  - Logistic Regression vs Random Forest: identical fraction = 0.569
  - Logistic Regression vs Random Forest SMOTE: identical fraction = 0.594
  - Logistic Regression vs ANN: identical fraction = 0.643
  - Logistic Regression vs ANN SMOTE: identical fraction = 0.701
  - Logistic Regression vs Stacking Classifier: identical fraction = 0.603
  - Logistic Regression SMOTE vs Random Forest: identical fraction = 0.566
  - Logistic Regression SMOTE vs Random Forest SMOTE: identical fraction = 0.592
  - Logistic Regression SMOTE vs ANN: identical fraction = 0.638
  - Logistic Regression SMOTE vs ANN SMOTE: identical fraction = 0.698
  - Logistic Regression SMOTE vs Stacking Classifier: identical fraction = 0.599
  - Random Forest vs Random Forest SMOTE: identical fraction = 0.935
  - Random Forest vs ANN: identical fraction = 0.826
  - Random Forest vs ANN SMOTE: identical fraction = 0.777
  - Random Forest vs Stacking Classifier: identical fraction = 0.885
  - Random Forest SMOTE vs ANN: identical fraction = 0.823
  - Random Forest SMOTE vs ANN SMOTE: identical fraction = 0.806
  - Random Forest SMOTE vs Stacking Classifier: identical fraction = 0.870
  - ANN vs ANN SMOTE: identical fraction = 0.873
  - ANN vs Stacking Classifier: identical fraction = 0.875
  - ANN SMOTE vs Stacking Classifier: identical fraction = 0.814

# Binary Classification (Charging State)

In [26]:
# Set the experiment in MLflow
mlflow.set_experiment('Binary Classification (Charging State)')

<Experiment: artifact_location='/Users/yannis/mlflow-artifacts/3', creation_time=1761300037818, experiment_id='3', last_update_time=1761300037818, lifecycle_stage='active', name='Binary Classification (Charging State)', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [27]:
# Load the sheet into a DataFrame
df = pd.read_csv(DATA_PATH)

# Display basic info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115298 entries, 0 to 115297
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           115298 non-null  object
 1   shunt_voltage  115298 non-null  int64
 2   bus_voltage_V  115298 non-null  float64
 3   current_mA     115298 non-null  int64
 4   power_mW       115298 non-null  int64
 5   State          115298 non-null  object
 6   Attack         115298 non-null  object
 7   Attack-Group   115298 non-null  object
 8   Label          115298 non-null  object
 9   interface      115298 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 8.8+ MB

In [28]:
# Define mapping dictionary
attack_mapping = {
    'syn-flood': 'DoS',
    'tcp-flood': 'DoS',
    'cryptojacking': 'Cryptojacking',
    'vuln-scan': 'Recon',
    'syn-stealth': 'Recon',
    'Backdoor': 'Backdoor',
    'none': 'Benign'
}

# Apply mapping to create 'Attack-New' column
df['Attack-New'] = df['Attack'].map(attack_mapping)

# Print the first rows of the DataFrame to verify the new column
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp,DoS
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp,DoS
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp,DoS
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp,DoS
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp,DoS

In [29]:
# Filter data for 'charging' state
df_charging = df[df['State'] == 'charging'].copy()

# Print the first few rows of the filtered DataFrame
df_charging.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
34884,12/26/2023 15:17,660,5.185,652,3380,charging,none,none,benign,none,Benign
34885,12/26/2023 15:17,769,5.189,675,3500,charging,none,none,benign,none,Benign
34886,12/26/2023 15:17,525,5.197,512,2660,charging,none,none,benign,none,Benign
34887,12/26/2023 15:17,690,5.181,642,3340,charging,none,none,benign,none,Benign
34888,12/26/2023 15:17,638,5.189,574,2780,charging,none,none,benign,none,Benign

In [30]:
# Convert "Attack-New" to binary: 1 = Attack, 0 = Benign
df_charging['Attack-Binary'] = df_charging['Attack-New'].apply(lambda x: 0 if x == 'Benign' else 1)

# Print the first rows of the DataFrame to verify the new column
df_charging.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New,Attack-Binary
34884,12/26/2023 15:17,660,5.185,652,3380,charging,none,none,benign,none,Benign,0
34885,12/26/2023 15:17,769,5.189,675,3500,charging,none,none,benign,none,Benign,0
34886,12/26/2023 15:17,525,5.197,512,2660,charging,none,none,benign,none,Benign,0
34887,12/26/2023 15:17,690,5.181,642,3340,charging,none,none,benign,none,Benign,0
34888,12/26/2023 15:17,638,5.189,574,2780,charging,none,none,benign,none,Benign,0

In [31]:
# Select numerical features for classification (excluding categorical columns)
numerical_features = ['shunt_voltage', 'bus_voltage_V', 'current_mA', 'power_mW']

# Define features (X) and target variable (Y)
X = df_charging[numerical_features]
Y = df_charging['Attack-Binary']

In [32]:
# Split the dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y, shuffle = True)

In [33]:
# Split the training set into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.2, random_state = 42, stratify = Y_train, shuffle = True)

In [34]:
# Set the encoder 
label_encoder = LabelEncoder()

# Encode 'Attack-New' labels as numbers for each subset
# Note: This is done after splitting to avoid data leakage
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_val_encoded = label_encoder.transform(Y_val)
Y_test_encoded = label_encoder.transform(Y_test)

# Check what each number represents
print('Label encoder classes:', label_encoder.classes_)

Label encoder classes: [0 1]

In [35]:
# Create the scaler
scaler = StandardScaler()

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Shape of the scaled data
print(f'Shape of X_train_scaled: {X_train_scaled.shape}')
print(f'Shape of X_val_scaled: {X_val_scaled.shape}')
print(f'Shape of X_test_scaled: {X_test_scaled.shape}')

Shape of X_train_scaled: (18939, 4)
Shape of X_val_scaled: (4735, 4)
Shape of X_test_scaled: (5919, 4)

In [ ]:
# Suppress specific warnings for cleaner output
warnings.filterwarnings('ignore', category = UserWarning)

# Models list
models_to_log = [
    ('KNN', MODELS_DIR + 'knn_bin_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('KNN SMOTE', MODELS_DIR + 'knn_bin_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('RBF SVM', MODELS_DIR + 'rbf_svm_bin_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('RBF SVM SMOTE', MODELS_DIR + 'rbf_svm_bin_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('XGBoost', MODELS_DIR + 'xgboost_bin_charging_best_model.json', 'xgboost', 'scaled', False),
    ('XGBoost SMOTE', MODELS_DIR + 'xgboost_bin_charging_smote_best_model.json', 'xgboost', 'scaled', True),
    ('Logistic Regression', MODELS_DIR + 'logistic_regression_bin_charging_best_model.pkl', 'sklearn', 'scaled', False),
    ('Logistic Regression SMOTE', MODELS_DIR + 'logistic_regression_bin_charging_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('Random Forest', MODELS_DIR + 'random_forest_bin_charging_best_model.pkl', 'sklearn', 'original', False),
    ('Random Forest SMOTE', MODELS_DIR + 'random_forest_bin_charging_smote_best_model.pkl', 'sklearn', 'original', True),
    ('ANN', MODELS_DIR + 'ann_bin_charging_model.keras', 'keras', 'scaled', False),
    ('ANN Weighted', MODELS_DIR + 'ann_bin_charging_weighted_model.keras', 'keras', 'scaled', False),
    ('ANN SMOTE', MODELS_DIR + 'ann_bin_charging_smote_model.keras', 'keras', 'scaled', True),
    ('Stacking Classifier', MODELS_DIR + 'stacking_clf_bin_charging_best_model.pkl', 'sklearn', 'original', False),
]

# Load production results CSV
# Clean CSV columns for MLflow logging
df_prod = pd.read_csv('df_production_results_bin_charging.csv')

# Ensure numeric
for col in ['Prediction Time (sec)','F1 Macro', 'Memory Used (kB)', 'CPU Time (sec)', 'Physical Cores', 'Logical Cores', 'CPU % Used (Raw)',
            'CPU % Used (Normalized)','Model Size (MB)']:
    df_prod[col] = pd.to_numeric(df_prod[col], errors = 'coerce')

# Sanity checks
required_globals = ['X_train', 'X_test', 'X_test_scaled', 'Y_test_encoded', 'label_encoder']
missing = [g for g in required_globals if g not in globals()]
if missing:
    raise RuntimeError(f'Please ensure these globals exist before running: {missing}')

# Helper functions
def ensure_dataframe(X, ref_columns):
    if isinstance(X, np.ndarray):
        return pd.DataFrame(X, columns = list(ref_columns))
    if isinstance(X, pd.DataFrame):
        if list(X.columns) != list(ref_columns) and X.shape[1] == len(ref_columns):
            return pd.DataFrame(X.values, columns = list(ref_columns))
        return X
    raise ValueError('X must be numpy array or pandas DataFrame')

def model_includes_scaler(model):
    if isinstance(model, Pipeline):
        for step in model.named_steps.values():
            cls_name = step.__class__.__name__.lower()
            if 'scaler' in cls_name or 'standardscaler' in cls_name or 'minmax' in cls_name or 'preprocessor' in cls_name:
                return True
    return False

def _safe_params_dict(params: dict, prefix = ''):
    safe = {}
    for k, v in params.items():
        key = f'{prefix}{k}'
        if isinstance(v, (str, int, float, bool)) or v is None:
            safe[key] = v
        else:
            try:
                s = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
                safe[key] = s[:200]
            except Exception:
                safe[key] = str(type(v))
    return safe

def keras_params_summary(model: keras.Model):
    params = {}
    try:
        params['keras_total_params'] = model.count_params()
    except Exception:
        params['keras_total_params'] = None
    params['keras_layers_count'] = len(model.layers)
    for i, layer in enumerate(model.layers):
        try:
            cfg = layer.get_config()
        except Exception:
            cfg = {}
        params[f'layer_{i}_class'] = layer.__class__.__name__
        if 'units' in cfg:
            params[f'layer_{i}_units'] = cfg.get('units')
        if 'activation' in cfg:
            params[f'layer_{i}_activation'] = cfg.get('activation')
    try:
        opt = model.optimizer.get_config()
        params['optimizer'] = model.optimizer.__class__.__name__
        for k, v in opt.items():
            params[f'opt_{k}'] = v if isinstance(v, (str, int, float, bool)) else str(v)
    except Exception:
        pass
    try:
        params['loss'] = model.loss if not callable(model.loss) else str(model.loss)
    except Exception:
        pass
    return params

def extract_xgb_from_pipeline(m):
    if not isinstance(m, Pipeline):
        return None
    for step in m.named_steps.values():
        cls = step.__class__.__name__.lower()
        if 'xgb' in cls or hasattr(step, 'get_xgb_params'):
            return step
    return None

def safe_head_example(X, n = 8):
    try:
        if isinstance(X, pd.DataFrame):
            return X.head(n)
        if isinstance(X, np.ndarray):
            return pd.DataFrame(X[:n], columns = X_train.columns)
    except Exception:
        pass
    return None

def safe_predict_for_signature(model, X_example, framework):
    try:
        fw = (framework or '').lower()
        if fw == 'keras':
            preds = model.predict(X_example, verbose = 0)
            return preds
        elif fw == 'xgboost':
            if isinstance(model, xgb.core.Booster):
                d = xgb.DMatrix(X_example)
                preds = model.predict(d)
                return preds
            else:
                if hasattr(model, 'predict'):
                    return model.predict(X_example)
        else:
            return model.predict(X_example)
    except Exception:
        return None

def safe_log_params_iter(obj, prefix = ''):
    safe = {}
    try:
        gp = obj.get_params()
        for k, v in gp.items():
            try:
                if isinstance(v, (list, dict)):
                    safe[f'{prefix}{k}'] = json.dumps(v)[:400]
                elif hasattr(v, '__name__') and getattr(v, '__name__'):
                    safe[f'{prefix}{k}'] = getattr(v, '__name__')
                else:
                    safe[f'{prefix}{k}'] = v
            except Exception:
                safe[f'{prefix}{k}'] = str(type(v))
    except Exception:
        pass
    return safe

def mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = None):
    fw = (framework or '').lower()
    example_df = safe_head_example(X_example) if X_example is not None else None

    input_example_np = None
    signature = None
    input_example = None

    if example_df is not None:
        input_example_np = example_df.values if isinstance(example_df, pd.DataFrame) else example_df
        input_example = input_example_np
        preds = safe_predict_for_signature(model, input_example_np, fw)
        try:
            signature = infer_signature(input_example_np, preds) if preds is not None else infer_signature(input_example_np, None)
        except Exception:
            signature = None

    with tempfile.TemporaryDirectory(prefix = 'mlflow_model_') as tmp_path:
        try:
            if fw == 'keras':
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                # Skip passing input_example here to avoid MLflow directory error
                try:
                    mlflow.keras.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception as e:
                    print('  -> Primary keras log_model failed:', e)
                    saved_path = os.path.join(tmp_path, 'model.keras')
                    os.makedirs(saved_path, exist_ok = True)
                    try:
                        model.save(saved_path, include_optimizer = True)
                    except Exception:
                        model.save(saved_path)
                    mlflow.log_artifact(saved_path, artifact_path = artifact_name)
                    return True

            elif fw == 'xgboost':
                inner = extract_xgb_from_pipeline(model) if isinstance(model, Pipeline) else None
                candidate = inner or model
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.xgboost.log_model(xgb_model = candidate, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                try:
                    if isinstance(candidate, xgb.core.Booster):
                        p = os.path.join(tmp_path, 'booster.json')
                        candidate.save_model(p)
                        mlflow.log_artifact(p, artifact_path = artifact_name)
                        return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

            else:
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.sklearn.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

        except Exception as e:
            print(f'mlflow_log_model_auto: primary path exception: {e}')
            return False

# Unified prediction/proba extractor (works for pipelines, sklearn, keras, xgboost)
def get_predictions_and_probas(model, framework, X_eval_df, label_encoder):
    """
    Return (y_pred_int_encoded, y_proba_for_auc_or_None)
    - y_pred: integer encoded (0/1 or 0..k-1)
    - y_proba_for_auc: 1D array of probability for positive class (binary) or numeric score usable by roc_auc_score
    """
    # Keras:
    if framework == 'keras':
        y_pred_proba = model.predict(X_eval_df, verbose=0)
        if y_pred_proba.ndim == 2 and y_pred_proba.shape[1] == 1:
            y_pred = (y_pred_proba.ravel() >= 0.5).astype(int)
            y_proba = y_pred_proba.ravel()
        else:
            # Multiclass softmax
            y_pred = np.argmax(y_pred_proba, axis = 1)
            # For multiclass AUC we might not compute here; for binary-case keep class 1 prob
            y_proba = y_pred_proba[:, 1] if y_pred_proba.shape[1] > 1 else y_pred_proba.ravel()
        return y_pred, y_proba

    # XGBoost: could be pipeline (with XGBClassifier inside), XGBClassifier object, or Booster saved
    if framework == 'xgboost':
        # If pipeline, pipeline.predict/predict_proba works
        try:
            # Prefer using predict_proba when exists
            if hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_eval_df)
                if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                    y_pred = np.argmax(y_proba, axis = 1)
                    y_proba_for_auc = y_proba[:, 1]
                else:
                    y_pred = (y_proba.ravel() > 0.5).astype(int)
                    y_proba_for_auc = y_proba.ravel()
                return y_pred, y_proba_for_auc
            # Else maybe a Booster object loaded via xgb.Booster
            if isinstance(model, xgb.core.Booster):
                dmat = xgb.DMatrix(X_eval_df)
                probs = model.predict(dmat)
                # Binary or multiclass shape?
                if probs.ndim == 1:
                    y_pred = (probs > 0.5).astype(int)
                    return y_pred, probs.ravel()
                else:
                    # Multiclass
                    y_pred = np.argmax(probs, axis = 1)
                    # Choose class-1 probability for AUC if exists
                    y_proba_for_auc = probs[:, 1] if probs.shape[1] > 1 else probs.ravel()
                    return y_pred, y_proba_for_auc
        except Exception:
            pass

        # Last fallback: try predict
        y_pred_raw = model.predict(X_eval_df)
        if isinstance(y_pred_raw[0], str):
            y_pred = label_encoder.transform(y_pred_raw)
        else:
            y_pred = np.asarray(y_pred_raw).astype(int)
        # Try predict_proba but wrap in try
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                return y_pred, y_proba[:, 1]
            else:
                return y_pred, y_proba.ravel()
        except Exception:
            return y_pred, None

    # SKLearn generic (includes pipelines)
    y_pred_raw = model.predict(X_eval_df)
    if isinstance(y_pred_raw[0], str):
        y_pred = label_encoder.transform(y_pred_raw)
    else:
        y_pred = np.asarray(y_pred_raw).astype(int)

    # Try predict_proba
    y_proba_for_auc = None
    if hasattr(model, 'predict_proba'):
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                y_proba_for_auc = y_proba[:, 1]
            else:
                y_proba_for_auc = y_proba.ravel()
        except Exception:
            y_proba_for_auc = None
    elif hasattr(model, 'decision_function'):
        try:
            dec = model.decision_function(X_eval_df)
            # scale to [0,1]
            dec = np.ravel(dec)
            if dec.max() != dec.min():
                y_proba_for_auc = (dec - dec.min()) / (dec.max() - dec.min())
            else:
                y_proba_for_auc = dec
        except Exception:
            y_proba_for_auc = None

    return y_pred, y_proba_for_auc

# Main loop
f1_average = 'macro'
predictions_dict = {}

for model_name, path, framework, data_type, used_smote in models_to_log:
    print('\n' + '=' * 70)
    print(f'Loading {model_name}...')

    # ---------- Load model ----------
    model = None
    xgb_params_loaded = None
    try:
        if framework == 'keras':
            model = keras.models.load_model(path)
        elif framework == 'xgboost':
            # Attempt joblib (pipeline or sklearn wrapper)
            try:
                model = joblib.load(path)
            except Exception:
                # Attempt XGBClassifier .load_model()
                try:
                    clf = xgb.XGBClassifier()
                    clf.load_model(path)
                    model = clf
                except Exception:
                    # Attempt Booster
                    try:
                        booster = xgb.Booster()
                        booster.load_model(path)
                        model = booster
                    except Exception as e:
                        raise e
            # Companion params file if present
            params_path = path.replace('.json', '_params.json')
            if os.path.exists(params_path):
                try:
                    with open(params_path, 'r') as f:
                        xgb_params_loaded = json.load(f)
                except Exception:
                    xgb_params_loaded = None
        else:
            model = joblib.load(path)
    except Exception as e:
        print(f'Error loading {model_name}: {e}')
        continue

    # ---------- Choose evaluation data ----------
    use_original_X = False
    if model_name == 'Stacking Classifier':
        X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
        reason = "Stacking Classifier: Using original 'X_test' (trained that way)"
    else:
        if framework != 'keras' and model_includes_scaler(model):
            X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
            reason = "Pipeline includes scaler: Using original 'X_test' (pipeline will scale)"
        else:
            X_eval = X_test_scaled if data_type == 'scaled' else X_test
            X_eval_df = ensure_dataframe(X_eval, ref_columns = X_train.columns)
            reason = f"Data type = '{data_type}': Using '{'X_test_scaled' if data_type == 'scaled' else 'X_test'}'"

    print('  ->', reason)

    # ---------- Predictions ----------
    try:
        y_pred, y_proba_for_auc = get_predictions_and_probas(model, framework, X_eval_df, label_encoder)
    except Exception as e:
        print(f'Prediction failed for {model_name}: {e}')
        continue

    # ---------- Metrics ----------
    y_true_enc = Y_test_encoded
    acc = accuracy_score(y_true_enc, y_pred)
    f1 = f1_score(y_true_enc, y_pred, average = f1_average)
    auc_val = None
    if y_proba_for_auc is not None:
        try:
            auc_val = roc_auc_score(y_true_enc, y_proba_for_auc)
        except Exception as e:
            print(f'  -> Warning: roc_auc_score failed: {e}; y_proba shape: {np.shape(y_proba_for_auc)}')

    # Print the metrics
    print(f'  -> Accuracy: {acc:.4f}, F1 ({f1_average}): {f1:.4f}, ROC AUC: {auc_val:.4f}')
    print('  -> Sample preds (first 10):', list(y_pred[:10]))
    unique, counts = np.unique(y_pred, return_counts = True)
    print('  -> Unique pred counts:', dict(zip(unique.tolist(), counts.tolist())))

    predictions_dict[model_name] = y_pred

    # ---------- MLflow logging ----------
    run_name = f'{model_name} Binary (Charging State)'
    with mlflow.start_run(run_name = run_name) as run:
        row = df_prod[df_prod['Model'] == model_name]
        if not row.empty:
            mlflow.log_metric('Prediction Time secs', float(row['Prediction Time (sec)'].iloc[0]))
          # mlflow.log_metric('Memory Used (kB)', float(row['Memory Used (kB)'].iloc[0]))
            mlflow.log_metric('CPU Time secs', float(row['CPU Time (sec)'].iloc[0]))
            mlflow.log_metric('Physical Cores', int(row['Physical Cores'].iloc[0]))
            mlflow.log_metric('Logical Cores', int(row['Logical Cores'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Raw', float(row['CPU % Used (Raw)'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Normalized', float(row['CPU % Used (Normalized)'].iloc[0]))
            mlflow.log_metric('Model Size MB', float(row['Model Size (MB)'].iloc[0]))
          # mlflow.log_metric('F1 Macro (CSV)', float(row['F1 Macro'])) # I log it from the model not the csv

        mlflow.log_metric('Accuracy', float(f'{acc:.4f}'))
        mlflow.log_metric('F1 macro', float(f'{f1:.4f}'))
        if auc_val is not None:
            mlflow.log_metric('ROC AUC', float(f'{auc_val:.4f}'))

        mlflow.log_param('SMOTE', bool(used_smote))
        mlflow.set_tag('SMOTE', str(bool(used_smote)))
        mlflow.log_param('Framework', framework)
        mlflow.log_param('ModelPath', path)

        # ---------- Log model parameters robustly ----------
        try:
            if framework == 'keras':
                kp = keras_params_summary(model)
                safe_kp = _safe_params_dict(kp, prefix = 'keras_')
                if safe_kp:
                    mlflow.log_params(safe_kp)

            elif framework == 'xgboost':
                if isinstance(model, Pipeline):
                    inner = extract_xgb_from_pipeline(model)
                    if inner:
                        try:
                            safe = safe_log_params_iter(inner, prefix = 'xgb_')
                            if safe:
                                mlflow.log_params(safe)
                        except Exception:
                            pass
                else:
                    try:
                        if hasattr(model, 'get_xgb_params'):
                            xp = model.get_xgb_params()
                            mlflow.log_params(_safe_params_dict(xp, prefix = 'xgb_'))
                    except Exception:
                        pass
                    try:
                        if hasattr(model, 'get_params'):
                            gp = model.get_params()
                            safe_gp = _safe_params_dict(gp, prefix = 'xgb_')
                            if safe_gp:
                                mlflow.log_params(safe_gp)
                    except Exception:
                        pass
                    if xgb_params_loaded:
                        mlflow.log_params(_safe_params_dict(xgb_params_loaded, prefix = 'xgb_file_'))

            elif 'stack' in model_name.lower() or hasattr(model, 'final_estimator_'):
                try:
                    # Meta estimator
                    if hasattr(model, 'final_estimator_'):
                        try:
                            meta_params = safe_log_params_iter(model.final_estimator_, prefix = 'meta_')
                            if meta_params:
                                mlflow.log_params(meta_params)
                        except Exception:
                            pass
                    # Base estimators: named_estimators_ or estimators_
                    if hasattr(model, 'named_estimators_'):
                        for name, est in model.named_estimators_.items():
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{name}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                # Skip problematic estimator param
                                pass
                    elif hasattr(model, 'estimators_'):
                        for i, est in enumerate(model.estimators_):
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{i}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                except Exception as e:
                    print('  -> Warning logging stacking params:', e)

            else:
                if hasattr(model, 'get_params'):
                    try:
                        gp = model.get_params()
                        mlflow.log_params(_safe_params_dict(gp))
                    except Exception:
                        if isinstance(model, Pipeline):
                            for name, step in model.named_steps.items():
                                if hasattr(step, 'get_params'):
                                    mlflow.log_params(_safe_params_dict(step.get_params(), prefix = f'{name}__'))
        except Exception as e:
            print('  -> Warning while preparing params to log:', e)

        # ---------- Classification report: safe JSON + text ----------
        try:
            ncls = len(np.unique(y_true_enc))
            if 'label_encoder' in globals() and len(label_encoder.classes_) == ncls:
                target_names = [str(s) for s in label_encoder.classes_]
            else:
                target_names = [str(int(x)) for x in np.unique(y_true_enc)]

            creport_dict = classification_report(y_true_enc, y_pred, output_dict = True)
            creport_text = classification_report(y_true_enc, y_pred, target_names = target_names)
            mlflow.log_text(json.dumps(creport_dict, indent = 4), 'classification_report.json')
            mlflow.log_text(creport_text, 'classification_report.txt')
        except Exception as e:
            print('  -> Warning logging classification report:', e)

        # ---------- Log model artifact robustly (with signatures & input_example) ----------
        try:
            logged_ok = mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = X_eval_df)
            if not logged_ok:
                print('  -> Warning: model artifact not logged via standard mlflow path and fallback.')
        except Exception as e:
            print('  -> Error logging model artifact:', e)

        # ---------- Print run link/info ----------
        try:
            run_id = run.info.run_id
            exp_id = run.info.experiment_id
            print(f'  -> MLflow run id: {run_id} (experiment {exp_id})')
        except Exception:
            pass

    print(f'✅ Logged {model_name} (SMOTE = {used_smote})')

# After loop: cross-model identical prediction check
print('\n' + '=' * 70)
print('Cross-model prediction overlap:')
names = list(predictions_dict.keys())
for i in range(len(names)):
    for j in range(i+1, len(names)):
        a, b = names[i], names[j]
        overlap = np.mean(predictions_dict[a] == predictions_dict[b])
        print(f'  - {a} vs {b}: identical fraction = {overlap:.3f}')

======================================================================
Loading KNN...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8461, F1 (macro): 0.7720, ROC AUC: 0.8828
  -> Sample preds (first 10): [1, 0, 1, 1, 1, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1156, 1: 4763}
  -> MLflow run id: e12a6d9407844bee91d5f48b4318dd77 (experiment 3)
🏃 View run KNN Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/e12a6d9407844bee91d5f48b4318dd77
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged KNN (SMOTE = False)

======================================================================
Loading KNN SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8104, F1 (macro): 0.7649, ROC AUC: 0.8775
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1925, 1: 3994}
  -> MLflow run id: a1188a16051347cab216dcffd08a54ed (experiment 3)
🏃 View run KNN SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/a1188a16051347cab216dcffd08a54ed
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged KNN SMOTE (SMOTE = True)

======================================================================
Loading RBF SVM...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8184, F1 (macro): 0.7171, ROC AUC: 0.8408
  -> Sample preds (first 10): [1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 988, 1: 4931}
  -> MLflow run id: 457620b9033e4fecb939db153eb02343 (experiment 3)
🏃 View run RBF SVM Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/457620b9033e4fecb939db153eb02343
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged RBF SVM (SMOTE = False)

======================================================================
Loading RBF SVM SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7368, F1 (macro): 0.7064, ROC AUC: 0.8566
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 2625, 1: 3294}
  -> MLflow run id: 1caf3efce74f45f4817af147572667be (experiment 3)
🏃 View run RBF SVM SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/1caf3efce74f45f4817af147572667be
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged RBF SVM SMOTE (SMOTE = True)

======================================================================
Loading XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8731, F1 (macro): 0.8103, ROC AUC: 0.9281
  -> Sample preds (first 10): [1, 1, 1, 1, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1124, 1: 4795}
  -> MLflow run id: 79e9abee810f4d4990aa527bf2b9fdec (experiment 3)
🏃 View run XGBoost Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/79e9abee810f4d4990aa527bf2b9fdec
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged XGBoost (SMOTE = False)

======================================================================
Loading XGBoost SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8542, F1 (macro): 0.8104, ROC AUC: 0.9265
  -> Sample preds (first 10): [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1686, 1: 4233}
  -> MLflow run id: e98d70f156f943f096d13dd2fa71e4a4 (experiment 3)
🏃 View run XGBoost SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/e98d70f156f943f096d13dd2fa71e4a4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged XGBoost SMOTE (SMOTE = True)

======================================================================
Loading Logistic Regression...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7290, F1 (macro): 0.6978, ROC AUC: 0.8433
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 2627, 1: 3292}
  -> MLflow run id: 688814ef09f04d1ba2ac717b521a037d (experiment 3)
🏃 View run Logistic Regression Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/688814ef09f04d1ba2ac717b521a037d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged Logistic Regression (SMOTE = False)

======================================================================
Loading Logistic Regression SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.7293, F1 (macro): 0.6979, ROC AUC: 0.8435
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 2621, 1: 3298}
  -> MLflow run id: 25a57c3cb4624e698a149494782e332a (experiment 3)
🏃 View run Logistic Regression SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/25a57c3cb4624e698a149494782e332a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged Logistic Regression SMOTE (SMOTE = True)

======================================================================
Loading Random Forest...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.8618, F1 (macro): 0.8096, ROC AUC: 0.9228
  -> Sample preds (first 10): [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1431, 1: 4488}
  -> MLflow run id: ace7b3dade5a4aee8a1751b65b2ebc8c (experiment 3)
🏃 View run Random Forest Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/ace7b3dade5a4aee8a1751b65b2ebc8c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged Random Forest (SMOTE = False)

======================================================================
Loading Random Forest SMOTE...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.8596, F1 (macro): 0.8073, ROC AUC: 0.9199
  -> Sample preds (first 10): [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1446, 1: 4473}
  -> MLflow run id: 771b1b6269154dd4823f32f7e726c19a (experiment 3)
🏃 View run Random Forest SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/771b1b6269154dd4823f32f7e726c19a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged Random Forest SMOTE (SMOTE = True)

======================================================================
Loading ANN...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8250, F1 (macro): 0.7384, ROC AUC: 0.8684
  -> Sample preds (first 10): [1, 0, 1, 0, 1, 0, 1, 1, 1, 1]
  -> Unique pred counts: {0: 1125, 1: 4794}
  -> MLflow run id: 11d39f2b32054c0988228c6a70f7b7c4 (experiment 3)
🏃 View run ANN Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/11d39f2b32054c0988228c6a70f7b7c4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged ANN (SMOTE = False)

======================================================================
Loading ANN Weighted...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.7425, F1 (macro): 0.7092, ROC AUC: 0.8648
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 2527, 1: 3392}
  -> MLflow run id: 6575a2cd87454b088a6421037564873f (experiment 3)
🏃 View run ANN Weighted Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/6575a2cd87454b088a6421037564873f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged ANN Weighted (SMOTE = False)

======================================================================
Loading ANN SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.7317, F1 (macro): 0.7014, ROC AUC: 0.8603
  -> Sample preds (first 10): [1, 0, 1, 0, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 2643, 1: 3276}
  -> MLflow run id: 057f77f0a87c41509b8d99f5facdb892 (experiment 3)
🏃 View run ANN SMOTE Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/057f77f0a87c41509b8d99f5facdb892
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged ANN SMOTE (SMOTE = True)

======================================================================
Loading Stacking Classifier...
  -> Stacking Classifier: Using original 'X_test' (trained that way)
  -> Accuracy: 0.8586, F1 (macro): 0.8130, ROC AUC: 0.9259
  -> Sample preds (first 10): [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
  -> Unique pred counts: {0: 1608, 1: 4311}
  -> MLflow run id: b91da1bc8b3d4a7f8a25693de47d7a07 (experiment 3)
🏃 View run Stacking Classifier Binary (Charging State) at: http://127.0.0.1:5000/#/experiments/3/runs/b91da1bc8b3d4a7f8a25693de47d7a07
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Logged Stacking Classifier (SMOTE = False)

======================================================================
Cross-model prediction overlap:
  - KNN vs KNN SMOTE: identical fraction = 0.870
  - KNN vs RBF SVM: identical fraction = 0.879
  - KNN vs RBF SVM SMOTE: identical fraction = 0.744
  - KNN vs XGBoost: identical fraction = 0.905
  - KNN vs XGBoost SMOTE: identical fraction = 0.872
  - KNN vs Logistic Regression: identical fraction = 0.736
  - KNN vs Logistic Regression SMOTE: identical fraction = 0.737
  - KNN vs Random Forest: identical fraction = 0.902
  - KNN vs Random Forest SMOTE: identical fraction = 0.905
  - KNN vs ANN: identical fraction = 0.882
  - KNN vs ANN Weighted: identical fraction = 0.758
  - KNN vs ANN SMOTE: identical fraction = 0.736
  - KNN vs Stacking Classifier: identical fraction = 0.897
  - KNN SMOTE vs RBF SVM: identical fraction = 0.800
  - KNN SMOTE vs RBF SVM SMOTE: identical fraction = 0.819
  - KNN SMOTE vs XGBoost: identical fraction = 0.838
  - KNN SMOTE vs XGBoost SMOTE: identical fraction = 0.870
  - KNN SMOTE vs Logistic Regression: identical fraction = 0.804
  - KNN SMOTE vs Logistic Regression SMOTE: identical fraction = 0.804
  - KNN SMOTE vs Random Forest: identical fraction = 0.874
  - KNN SMOTE vs Random Forest SMOTE: identical fraction = 0.880
  - KNN SMOTE vs ANN: identical fraction = 0.811
  - KNN SMOTE vs ANN Weighted: identical fraction = 0.832
  - KNN SMOTE vs ANN SMOTE: identical fraction = 0.819
  - KNN SMOTE vs Stacking Classifier: identical fraction = 0.892
  - RBF SVM vs RBF SVM SMOTE: identical fraction = 0.723
  - RBF SVM vs XGBoost: identical fraction = 0.875
  - RBF SVM vs XGBoost SMOTE: identical fraction = 0.812
  - RBF SVM vs Logistic Regression: identical fraction = 0.720
  - RBF SVM vs Logistic Regression SMOTE: identical fraction = 0.721
  - RBF SVM vs Random Forest: identical fraction = 0.847
  - RBF SVM vs Random Forest SMOTE: identical fraction = 0.847
  - RBF SVM vs ANN: identical fraction = 0.938
  - RBF SVM vs ANN Weighted: identical fraction = 0.740
  - RBF SVM vs ANN SMOTE: identical fraction = 0.720
  - RBF SVM vs Stacking Classifier: identical fraction = 0.832
  - RBF SVM SMOTE vs XGBoost: identical fraction = 0.744
  - RBF SVM SMOTE vs XGBoost SMOTE: identical fraction = 0.811
  - RBF SVM SMOTE vs Logistic Regression: identical fraction = 0.967
  - RBF SVM SMOTE vs Logistic Regression SMOTE: identical fraction = 0.967
  - RBF SVM SMOTE vs Random Forest: identical fraction = 0.780
  - RBF SVM SMOTE vs Random Forest SMOTE: identical fraction = 0.782
  - RBF SVM SMOTE vs ANN: identical fraction = 0.747
  - RBF SVM SMOTE vs ANN Weighted: identical fraction = 0.928
  - RBF SVM SMOTE vs ANN SMOTE: identical fraction = 0.944
  - RBF SVM SMOTE vs Stacking Classifier: identical fraction = 0.804
  - XGBoost vs XGBoost SMOTE: identical fraction = 0.903
  - XGBoost vs Logistic Regression: identical fraction = 0.736
  - XGBoost vs Logistic Regression SMOTE: identical fraction = 0.737
  - XGBoost vs Random Forest: identical fraction = 0.932
  - XGBoost vs Random Forest SMOTE: identical fraction = 0.924
  - XGBoost vs ANN: identical fraction = 0.882
  - XGBoost vs ANN Weighted: identical fraction = 0.751
  - XGBoost vs ANN SMOTE: identical fraction = 0.732
  - XGBoost vs Stacking Classifier: identical fraction = 0.917
  - XGBoost SMOTE vs Logistic Regression: identical fraction = 0.795
  - XGBoost SMOTE vs Logistic Regression SMOTE: identical fraction = 0.795
  - XGBoost SMOTE vs Random Forest: identical fraction = 0.928
  - XGBoost SMOTE vs Random Forest SMOTE: identical fraction = 0.927
  - XGBoost SMOTE vs ANN: identical fraction = 0.825
  - XGBoost SMOTE vs ANN Weighted: identical fraction = 0.814
  - XGBoost SMOTE vs ANN SMOTE: identical fraction = 0.802
  - XGBoost SMOTE vs Stacking Classifier: identical fraction = 0.948
  - Logistic Regression vs Logistic Regression SMOTE: identical fraction = 0.998
  - Logistic Regression vs Random Forest: identical fraction = 0.770
  - Logistic Regression vs Random Forest SMOTE: identical fraction = 0.772
  - Logistic Regression vs ANN: identical fraction = 0.742
  - Logistic Regression vs ANN Weighted: identical fraction = 0.914
  - Logistic Regression vs ANN SMOTE: identical fraction = 0.931
  - Logistic Regression vs Stacking Classifier: identical fraction = 0.791
  - Logistic Regression SMOTE vs Random Forest: identical fraction = 0.770
  - Logistic Regression SMOTE vs Random Forest SMOTE: identical fraction = 0.773
  - Logistic Regression SMOTE vs ANN: identical fraction = 0.744
  - Logistic Regression SMOTE vs ANN Weighted: identical fraction = 0.914
  - Logistic Regression SMOTE vs ANN SMOTE: identical fraction = 0.931
  - Logistic Regression SMOTE vs Stacking Classifier: identical fraction = 0.791
  - Random Forest vs Random Forest SMOTE: identical fraction = 0.957
  - Random Forest vs ANN: identical fraction = 0.855
  - Random Forest vs ANN Weighted: identical fraction = 0.788
  - Random Forest vs ANN SMOTE: identical fraction = 0.767
  - Random Forest vs Stacking Classifier: identical fraction = 0.963
  - Random Forest SMOTE vs ANN: identical fraction = 0.856
  - Random Forest SMOTE vs ANN Weighted: identical fraction = 0.792
  - Random Forest SMOTE vs ANN SMOTE: identical fraction = 0.773
  - Random Forest SMOTE vs Stacking Classifier: identical fraction = 0.951
  - ANN vs ANN Weighted: identical fraction = 0.763
  - ANN vs ANN SMOTE: identical fraction = 0.744
  - ANN vs Stacking Classifier: identical fraction = 0.844
  - ANN Weighted vs ANN SMOTE: identical fraction = 0.920
  - ANN Weighted vs Stacking Classifier: identical fraction = 0.812
  - ANN SMOTE vs Stacking Classifier: identical fraction = 0.793

# Binary Classification (Both States)

In [37]:
# Set the experiment in MLflow
mlflow.set_experiment('Binary Classification (Both States)')

<Experiment: artifact_location='/Users/yannis/mlflow-artifacts/4', creation_time=1761300495818, experiment_id='4', last_update_time=1761300495818, lifecycle_stage='active', name='Binary Classification (Both States)', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [38]:
# Load the sheet into a DataFrame
df = pd.read_csv(DATA_PATH)

# Display basic info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115298 entries, 0 to 115297
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           115298 non-null  object
 1   shunt_voltage  115298 non-null  int64
 2   bus_voltage_V  115298 non-null  float64
 3   current_mA     115298 non-null  int64
 4   power_mW       115298 non-null  int64
 5   State          115298 non-null  object
 6   Attack         115298 non-null  object
 7   Attack-Group   115298 non-null  object
 8   Label          115298 non-null  object
 9   interface      115298 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 8.8+ MB

In [39]:
# Define mapping dictionary
attack_mapping = {
    'syn-flood': 'DoS',
    'tcp-flood': 'DoS',
    'cryptojacking': 'Cryptojacking',
    'vuln-scan': 'Recon',
    'syn-stealth': 'Recon',
    'Backdoor': 'Backdoor',
    'none': 'Benign'
}

# Apply mapping to create 'Attack-New' column
df['Attack-New'] = df['Attack'].map(attack_mapping)

# Print the first rows of the DataFrame to verify the new column
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp,DoS
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp,DoS
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp,DoS
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp,DoS
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp,DoS

In [40]:
# Convert "Attack-New" to binary: 1 = Attack, 0 = Benign
df['Attack-Binary'] = df['Attack-New'].apply(lambda x: 0 if x == 'Benign' else 1)

# Print the first few rows of the DataFrame to verify the new column
df.head()

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface,Attack-New,Attack-Binary
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp,DoS,1
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp,DoS,1
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp,DoS,1
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp,DoS,1
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp,DoS,1

In [41]:
# Select numerical features for classification
numerical_features = ['shunt_voltage', 'bus_voltage_V', 'current_mA', 'power_mW']

# Define features (X) and target variable (Y)
X = df[numerical_features]
Y = df['Attack-Binary']

In [42]:
# Split the dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y, shuffle = True)

In [43]:
# Split the training set into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.2, random_state = 42, stratify = Y_train, shuffle = True)

In [44]:
# Set the encoder 
label_encoder = LabelEncoder()

# Encode 'Attack-New' labels as numbers for each subset
# Note: This is done after splitting to avoid data leakage
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_val_encoded = label_encoder.transform(Y_val)
Y_test_encoded = label_encoder.transform(Y_test)

# Check what each number represents
print('Label encoder classes:', label_encoder.classes_)

Label encoder classes: [0 1]

In [45]:
# Create the scaler
scaler = StandardScaler()

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Shape of the scaled data
print(f'Shape of X_train_scaled: {X_train_scaled.shape}')
print(f'Shape of X_val_scaled: {X_val_scaled.shape}')
print(f'Shape of X_test_scaled: {X_test_scaled.shape}')

Shape of X_train_scaled: (73790, 4)
Shape of X_val_scaled: (18448, 4)
Shape of X_test_scaled: (23060, 4)

In [ ]:
# Suppress specific warnings for cleaner output
warnings.filterwarnings('ignore', category = UserWarning)

# Models list
models_to_log = [
    ('KNN', MODELS_DIR + 'knn_bin_both_best_model.pkl', 'sklearn', 'scaled', False),
    ('KNN SMOTE', MODELS_DIR + 'knn_bin_both_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('XGBoost', MODELS_DIR + 'xgboost_bin_both_best_model.json', 'xgboost', 'scaled', False),
    ('XGBoost SMOTE', MODELS_DIR + 'xgboost_bin_both_smote_best_model.json', 'xgboost', 'scaled', True),
    ('Logistic Regression', MODELS_DIR + 'logistic_regression_bin_both_best_model.pkl', 'sklearn', 'scaled', False),
    ('Logistic Regression SMOTE', MODELS_DIR + 'logistic_regression_bin_both_smote_best_model.pkl', 'sklearn', 'scaled', True),
    ('Random Forest', MODELS_DIR + 'random_forest_bin_both_best_model.pkl', 'sklearn', 'original', False),
    ('Random Forest SMOTE', MODELS_DIR + 'random_forest_bin_both_smote_best_model.pkl', 'sklearn', 'original', True),
    ('ANN', MODELS_DIR + 'ann_bin_both_model.keras', 'keras', 'scaled', False),
    ('ANN Weighted', MODELS_DIR + 'ann_bin_both_weighted_model.keras', 'keras', 'scaled', False),
    ('ANN SMOTE', MODELS_DIR + 'ann_bin_both_smote_model.keras', 'keras', 'scaled', True),
    ('Stacking Classifier', MODELS_DIR + 'stacking_clf_bin_both_best_model.pkl', 'sklearn', 'original', False),
]

# Load production results CSV
# Clean CSV columns for MLflow logging
df_prod = pd.read_csv('df_production_results_bin_both.csv')

# Ensure numeric
for col in ['Prediction Time (sec)','F1 Macro', 'Memory Used (kB)', 'CPU Time (sec)', 'Physical Cores', 'Logical Cores', 'CPU % Used (Raw)',
            'CPU % Used (Normalized)','Model Size (MB)']:
    df_prod[col] = pd.to_numeric(df_prod[col], errors = 'coerce')

# Sanity checks
required_globals = ['X_train', 'X_test', 'X_test_scaled', 'Y_test_encoded', 'label_encoder']
missing = [g for g in required_globals if g not in globals()]
if missing:
    raise RuntimeError(f'Please ensure these globals exist before running: {missing}')

# Helper functions
def ensure_dataframe(X, ref_columns):
    if isinstance(X, np.ndarray):
        return pd.DataFrame(X, columns = list(ref_columns))
    if isinstance(X, pd.DataFrame):
        if list(X.columns) != list(ref_columns) and X.shape[1] == len(ref_columns):
            return pd.DataFrame(X.values, columns = list(ref_columns))
        return X
    raise ValueError('X must be numpy array or pandas DataFrame')

def model_includes_scaler(model):
    if isinstance(model, Pipeline):
        for step in model.named_steps.values():
            cls_name = step.__class__.__name__.lower()
            if 'scaler' in cls_name or 'standardscaler' in cls_name or 'minmax' in cls_name or 'preprocessor' in cls_name:
                return True
    return False

def _safe_params_dict(params: dict, prefix = ''):
    safe = {}
    for k, v in params.items():
        key = f'{prefix}{k}'
        if isinstance(v, (str, int, float, bool)) or v is None:
            safe[key] = v
        else:
            try:
                s = json.dumps(v) if isinstance(v, (dict, list)) else str(v)
                safe[key] = s[:200]
            except Exception:
                safe[key] = str(type(v))
    return safe

def keras_params_summary(model: keras.Model):
    params = {}
    try:
        params['keras_total_params'] = model.count_params()
    except Exception:
        params['keras_total_params'] = None
    params['keras_layers_count'] = len(model.layers)
    for i, layer in enumerate(model.layers):
        try:
            cfg = layer.get_config()
        except Exception:
            cfg = {}
        params[f'layer_{i}_class'] = layer.__class__.__name__
        if 'units' in cfg:
            params[f'layer_{i}_units'] = cfg.get('units')
        if 'activation' in cfg:
            params[f'layer_{i}_activation'] = cfg.get('activation')
    try:
        opt = model.optimizer.get_config()
        params['optimizer'] = model.optimizer.__class__.__name__
        for k, v in opt.items():
            params[f'opt_{k}'] = v if isinstance(v, (str, int, float, bool)) else str(v)
    except Exception:
        pass
    try:
        params['loss'] = model.loss if not callable(model.loss) else str(model.loss)
    except Exception:
        pass
    return params

def extract_xgb_from_pipeline(m):
    if not isinstance(m, Pipeline):
        return None
    for step in m.named_steps.values():
        cls = step.__class__.__name__.lower()
        if 'xgb' in cls or hasattr(step, 'get_xgb_params'):
            return step
    return None

def safe_head_example(X, n=8):
    try:
        if isinstance(X, pd.DataFrame):
            return X.head(n)
        if isinstance(X, np.ndarray):
            return pd.DataFrame(X[:n], columns = X_train.columns)
    except Exception:
        pass
    return None

def safe_predict_for_signature(model, X_example, framework):
    try:
        fw = (framework or "").lower()
        if fw == 'keras':
            preds = model.predict(X_example, verbose = 0)
            return preds
        elif fw == 'xgboost':
            if isinstance(model, xgb.core.Booster):
                d = xgb.DMatrix(X_example)
                preds = model.predict(d)
                return preds
            else:
                if hasattr(model, 'predict'):
                    return model.predict(X_example)
        else:
            return model.predict(X_example)
    except Exception:
        return None

def safe_log_params_iter(obj, prefix = ''):
    safe = {}
    try:
        gp = obj.get_params()
        for k, v in gp.items():
            try:
                if isinstance(v, (list, dict)):
                    safe[f'{prefix}{k}'] = json.dumps(v)[:400]
                elif hasattr(v, '__name__') and getattr(v, '__name__'):
                    safe[f'{prefix}{k}'] = getattr(v, '__name__')
                else:
                    safe[f'{prefix}{k}'] = v
            except Exception:
                safe[f'{prefix}{k}'] = str(type(v))
    except Exception:
        pass
    return safe

def mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = None):
    fw = (framework or '').lower()
    example_df = safe_head_example(X_example) if X_example is not None else None

    input_example_np = None
    signature = None
    input_example = None

    if example_df is not None:
        input_example_np = example_df.values if isinstance(example_df, pd.DataFrame) else example_df
        input_example = input_example_np
        preds = safe_predict_for_signature(model, input_example_np, fw)
        try:
            signature = infer_signature(input_example_np, preds) if preds is not None else infer_signature(input_example_np, None)
        except Exception:
            signature = None

    with tempfile.TemporaryDirectory(prefix = 'mlflow_model_') as tmp_path:
        try:
            if fw == 'keras':
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                # Skip passing input_example here to avoid MLflow directory error
                try:
                    mlflow.keras.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception as e:
                    print('  -> Primary keras log_model failed:', e)
                    saved_path = os.path.join(tmp_path, 'model.keras')
                    os.makedirs(saved_path, exist_ok = True)
                    try:
                        model.save(saved_path, include_optimizer = True)
                    except Exception:
                        model.save(saved_path)
                    mlflow.log_artifact(saved_path, artifact_path = artifact_name)
                    return True

            elif fw == 'xgboost':
                inner = extract_xgb_from_pipeline(model) if isinstance(model, Pipeline) else None
                candidate = inner or model
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.xgboost.log_model(xgb_model = candidate, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                try:
                    if isinstance(candidate, xgb.core.Booster):
                        p = os.path.join(tmp_path, 'booster.json')
                        candidate.save_model(p)
                        mlflow.log_artifact(p, artifact_path = artifact_name)
                        return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

            else:
                kwargs = {}
                if signature is not None:
                    kwargs['signature'] = signature
                if input_example is not None:
                    kwargs['input_example'] = input_example
                try:
                    mlflow.sklearn.log_model(model, name = artifact_name, **kwargs)
                    return True
                except Exception:
                    pass
                pkl = os.path.join(tmp_path, 'model_joblib.pkl')
                joblib.dump(model, pkl)
                mlflow.log_artifact(pkl, artifact_path = artifact_name)
                return True

        except Exception as e:
            print(f'mlflow_log_model_auto: primary path exception: {e}')
            return False

# Unified prediction/proba extractor (works for pipelines, sklearn, keras, xgboost)
def get_predictions_and_probas(model, framework, X_eval_df, label_encoder):
    """
    Return (y_pred_int_encoded, y_proba_for_auc_or_None)
    - y_pred: integer encoded (0/1 or 0..k-1)
    - y_proba_for_auc: 1D array of probability for positive class (binary) or numeric score usable by roc_auc_score
    """
    # Keras:
    if framework == 'keras':
        y_pred_proba = model.predict(X_eval_df, verbose = 0)
        if y_pred_proba.ndim == 2 and y_pred_proba.shape[1] == 1:
            y_pred = (y_pred_proba.ravel() >= 0.5).astype(int)
            y_proba = y_pred_proba.ravel()
        else:
            # Multiclass softmax
            y_pred = np.argmax(y_pred_proba, axis = 1)
            # For multiclass AUC we might not compute here; for binary-case keep class 1 prob
            y_proba = y_pred_proba[:, 1] if y_pred_proba.shape[1] > 1 else y_pred_proba.ravel()
        return y_pred, y_proba

    # XGBoost: could be pipeline (with XGBClassifier inside), XGBClassifier object, or Booster saved
    if framework == 'xgboost':
        # If pipeline, pipeline.predict/predict_proba works
        try:
            # Prefer using predict_proba when exists
            if hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_eval_df)
                if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                    y_pred = np.argmax(y_proba, axis=1)
                    y_proba_for_auc = y_proba[:, 1]
                else:
                    y_pred = (y_proba.ravel() > 0.5).astype(int)
                    y_proba_for_auc = y_proba.ravel()
                return y_pred, y_proba_for_auc
            # Else maybe a Booster object loaded via xgb.Booster
            if isinstance(model, xgb.core.Booster):
                dmat = xgb.DMatrix(X_eval_df)
                probs = model.predict(dmat)
                # Binary or multiclass shape?
                if probs.ndim == 1:
                    y_pred = (probs > 0.5).astype(int)
                    return y_pred, probs.ravel()
                else:
                    # Multiclass
                    y_pred = np.argmax(probs, axis = 1)
                    # Choose class-1 probability for AUC if exists
                    y_proba_for_auc = probs[:, 1] if probs.shape[1] > 1 else probs.ravel()
                    return y_pred, y_proba_for_auc
        except Exception:
            pass

        # Last fallback: try predict
        y_pred_raw = model.predict(X_eval_df)
        if isinstance(y_pred_raw[0], str):
            y_pred = label_encoder.transform(y_pred_raw)
        else:
            y_pred = np.asarray(y_pred_raw).astype(int)
        # Try predict_proba but wrap in try
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                return y_pred, y_proba[:, 1]
            else:
                return y_pred, y_proba.ravel()
        except Exception:
            return y_pred, None

    # SKLearn generic (includes pipelines)
    y_pred_raw = model.predict(X_eval_df)
    if isinstance(y_pred_raw[0], str):
        y_pred = label_encoder.transform(y_pred_raw)
    else:
        y_pred = np.asarray(y_pred_raw).astype(int)

    # Try predict_proba
    y_proba_for_auc = None
    if hasattr(model, 'predict_proba'):
        try:
            y_proba = model.predict_proba(X_eval_df)
            if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
                y_proba_for_auc = y_proba[:, 1]
            else:
                y_proba_for_auc = y_proba.ravel()
        except Exception:
            y_proba_for_auc = None
    elif hasattr(model, 'decision_function'):
        try:
            dec = model.decision_function(X_eval_df)
            # scale to [0,1]
            dec = np.ravel(dec)
            if dec.max() != dec.min():
                y_proba_for_auc = (dec - dec.min()) / (dec.max() - dec.min())
            else:
                y_proba_for_auc = dec
        except Exception:
            y_proba_for_auc = None

    return y_pred, y_proba_for_auc

# Main loop
f1_average = 'macro'
predictions_dict = {}

for model_name, path, framework, data_type, used_smote in models_to_log:
    print('\n' + '=' * 70)
    print(f'Loading {model_name}...')

    # ---------- Load model ----------
    model = None
    xgb_params_loaded = None
    try:
        if framework == 'keras':
            model = keras.models.load_model(path)
        elif framework == 'xgboost':
            # Attempt joblib (pipeline or sklearn wrapper)
            try:
                model = joblib.load(path)
            except Exception:
                # Attempt XGBClassifier .load_model()
                try:
                    clf = xgb.XGBClassifier()
                    clf.load_model(path)
                    model = clf
                except Exception:
                    # Attempt Booster
                    try:
                        booster = xgb.Booster()
                        booster.load_model(path)
                        model = booster
                    except Exception as e:
                        raise e
            # Companion params file if present
            params_path = path.replace('.json', '_params.json')
            if os.path.exists(params_path):
                try:
                    with open(params_path, 'r') as f:
                        xgb_params_loaded = json.load(f)
                except Exception:
                    xgb_params_loaded = None
        else:
            model = joblib.load(path)
    except Exception as e:
        print(f'Error loading {model_name}: {e}')
        continue

    # ---------- Choose evaluation data ----------
    use_original_X = False
    if model_name == 'Stacking Classifier':
        X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
        reason = "Stacking Classifier: Using original 'X_test' (trained that way)"
    else:
        if framework != 'keras' and model_includes_scaler(model):
            X_eval_df = ensure_dataframe(X_test, ref_columns = X_train.columns)
            reason = "Pipeline includes scaler: Using original 'X_test' (pipeline will scale)"
        else:
            X_eval = X_test_scaled if data_type == 'scaled' else X_test
            X_eval_df = ensure_dataframe(X_eval, ref_columns = X_train.columns)
            reason = f"Data type = '{data_type}': Using '{'X_test_scaled' if data_type == 'scaled' else 'X_test'}'"

    print('  ->', reason)

    # ---------- Predictions ----------
    try:
        y_pred, y_proba_for_auc = get_predictions_and_probas(model, framework, X_eval_df, label_encoder)
    except Exception as e:
        print(f'Prediction failed for {model_name}: {e}')
        continue

    # ---------- Metrics ----------
    y_true_enc = Y_test_encoded
    acc = accuracy_score(y_true_enc, y_pred)
    f1 = f1_score(y_true_enc, y_pred, average = f1_average)
    auc_val = None
    if y_proba_for_auc is not None:
        try:
            auc_val = roc_auc_score(y_true_enc, y_proba_for_auc)
        except Exception as e:
            print(f'  -> Warning: roc_auc_score failed: {e}; y_proba shape: {np.shape(y_proba_for_auc)}')

    # Print the metrics
    print(f'  -> Accuracy: {acc:.4f}, F1 ({f1_average}): {f1:.4f}, ROC AUC: {auc_val:.4f}')
    print('  -> Sample preds (first 10):', list(y_pred[:10]))
    unique, counts = np.unique(y_pred, return_counts = True)
    print('  -> Unique pred counts:', dict(zip(unique.tolist(), counts.tolist())))

    predictions_dict[model_name] = y_pred

    # ---------- MLflow logging ----------
    run_name = f'{model_name} Binary (Both States)'
    with mlflow.start_run(run_name = run_name) as run:
        row = df_prod[df_prod['Model'] == model_name]
        if not row.empty:
            mlflow.log_metric('Prediction Time secs', float(row['Prediction Time (sec)'].iloc[0]))
          # mlflow.log_metric('Memory Used (kB)', float(row['Memory Used (kB)'].iloc[0]))
            mlflow.log_metric('CPU Time secs', float(row['CPU Time (sec)'].iloc[0]))
            mlflow.log_metric('Physical Cores', int(row['Physical Cores'].iloc[0]))
            mlflow.log_metric('Logical Cores', int(row['Logical Cores'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Raw', float(row['CPU % Used (Raw)'].iloc[0]))
            mlflow.log_metric('CPU Percentage Used Normalized', float(row['CPU % Used (Normalized)'].iloc[0]))
            mlflow.log_metric('Model Size MB', float(row['Model Size (MB)'].iloc[0]))
          # mlflow.log_metric('F1 Macro (CSV)', float(row['F1 Macro'])) # I log it from the model not the csv
          
        mlflow.log_metric('Accuracy', float(f'{acc:.4f}'))
        mlflow.log_metric('F1 macro', float(f'{f1:.4f}'))
        if auc_val is not None:
            mlflow.log_metric('ROC AUC', float(f'{auc_val:.4f}'))

        mlflow.log_param('SMOTE', bool(used_smote))
        mlflow.set_tag('SMOTE', str(bool(used_smote)))
        mlflow.log_param('Framework', framework)
        mlflow.log_param('ModelPath', path)

        # ---------- Log model parameters robustly ----------
        try:
            if framework == 'keras':
                kp = keras_params_summary(model)
                safe_kp = _safe_params_dict(kp, prefix = 'keras_')
                if safe_kp:
                    mlflow.log_params(safe_kp)

            elif framework == 'xgboost':
                if isinstance(model, Pipeline):
                    inner = extract_xgb_from_pipeline(model)
                    if inner:
                        try:
                            safe = safe_log_params_iter(inner, prefix = 'xgb_')
                            if safe:
                                mlflow.log_params(safe)
                        except Exception:
                            pass
                else:
                    try:
                        if hasattr(model, 'get_xgb_params'):
                            xp = model.get_xgb_params()
                            mlflow.log_params(_safe_params_dict(xp, prefix = 'xgb_'))
                    except Exception:
                        pass
                    try:
                        if hasattr(model, 'get_params'):
                            gp = model.get_params()
                            safe_gp = _safe_params_dict(gp, prefix = 'xgb_')
                            if safe_gp:
                                mlflow.log_params(safe_gp)
                    except Exception:
                        pass
                    if xgb_params_loaded:
                        mlflow.log_params(_safe_params_dict(xgb_params_loaded, prefix = 'xgb_file_'))

            elif 'stack' in model_name.lower() or hasattr(model, 'final_estimator_'):
                try:
                    # Meta estimator
                    if hasattr(model, 'final_estimator_'):
                        try:
                            meta_params = safe_log_params_iter(model.final_estimator_, prefix = 'meta_')
                            if meta_params:
                                mlflow.log_params(meta_params)
                        except Exception:
                            pass
                    # Base estimators: named_estimators_ or estimators_
                    if hasattr(model, 'named_estimators_'):
                        for name, est in model.named_estimators_.items():
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{name}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                # Skip problematic estimator param
                                pass
                    elif hasattr(model, 'estimators_'):
                        for i, est in enumerate(model.estimators_):
                            try:
                                est_params = safe_log_params_iter(est, prefix = f'base_{i}_')
                                if est_params:
                                    mlflow.log_params(est_params)
                            except Exception:
                                pass
                except Exception as e:
                    print('  -> Warning logging stacking params:', e)

            else:
                if hasattr(model, 'get_params'):
                    try:
                        gp = model.get_params()
                        mlflow.log_params(_safe_params_dict(gp))
                    except Exception:
                        if isinstance(model, Pipeline):
                            for name, step in model.named_steps.items():
                                if hasattr(step, 'get_params'):
                                    mlflow.log_params(_safe_params_dict(step.get_params(), prefix = f'{name}__'))
        except Exception as e:
            print('  -> Warning while preparing params to log:', e)

        # ---------- Classification report: safe JSON + text ----------
        try:
            ncls = len(np.unique(y_true_enc))
            if 'label_encoder' in globals() and len(label_encoder.classes_) == ncls:
                target_names = [str(s) for s in label_encoder.classes_]
            else:
                target_names = [str(int(x)) for x in np.unique(y_true_enc)]

            creport_dict = classification_report(y_true_enc, y_pred, output_dict = True)
            creport_text = classification_report(y_true_enc, y_pred, target_names = target_names)
            mlflow.log_text(json.dumps(creport_dict, indent = 4), 'classification_report.json')
            mlflow.log_text(creport_text, 'classification_report.txt')
        except Exception as e:
            print('  -> Warning logging classification report:', e)

        # ---------- Log model artifact robustly (with signatures & input_example) ----------
        try:
            logged_ok = mlflow_log_model_auto(model, framework, artifact_name = 'model', X_example = X_eval_df)
            if not logged_ok:
                print('  -> Warning: model artifact not logged via standard mlflow path and fallback.')
        except Exception as e:
            print('  -> Error logging model artifact:', e)

        # ---------- Print run link/info ----------
        try:
            run_id = run.info.run_id
            exp_id = run.info.experiment_id
            print(f'  -> MLflow run id: {run_id} (experiment {exp_id})')
        except Exception:
            pass

    print(f'✅ Logged {model_name} (SMOTE = {used_smote})')

# After loop: cross-model identical prediction check
print('\n' + '=' * 70)
print('Cross-model prediction overlap:')
names = list(predictions_dict.keys())
for i in range(len(names)):
    for j in range(i+1, len(names)):
        a, b = names[i], names[j]
        overlap = np.mean(predictions_dict[a] == predictions_dict[b])
        print(f'  - {a} vs {b}: identical fraction = {overlap:.3f}')

======================================================================
Loading KNN...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.9378, F1 (macro): 0.8484, ROC AUC: 0.9432
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2480, 1: 20580}
  -> MLflow run id: f021580d70c44f33bc0c6946f21699e5 (experiment 4)
🏃 View run KNN Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/f021580d70c44f33bc0c6946f21699e5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged KNN (SMOTE = False)

======================================================================
Loading KNN SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.9058, F1 (macro): 0.8164, ROC AUC: 0.9286
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 4098, 1: 18962}
  -> MLflow run id: c696a970ca914294b7dc0e07b0b08529 (experiment 4)
🏃 View run KNN SMOTE Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/c696a970ca914294b7dc0e07b0b08529
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged KNN SMOTE (SMOTE = True)

======================================================================
Loading XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9478, F1 (macro): 0.8723, ROC AUC: 0.9743
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2450, 1: 20610}
  -> MLflow run id: 4da032518544445f95ba0f25232f1611 (experiment 4)
🏃 View run XGBoost Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/4da032518544445f95ba0f25232f1611
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged XGBoost (SMOTE = False)

======================================================================
Loading XGBoost SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9130, F1 (macro): 0.8348, ROC AUC: 0.9731
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 4323, 1: 18737}
  -> MLflow run id: cef66c4d9d1143ad883dc96471988e3f (experiment 4)
🏃 View run XGBoost SMOTE Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/cef66c4d9d1143ad883dc96471988e3f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged XGBoost SMOTE (SMOTE = True)

======================================================================
Loading Improved XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9484, F1 (macro): 0.8737, ROC AUC: 0.9743
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2456, 1: 20604}
  -> MLflow run id: 525942e819e94328a11cd8c632969f5b (experiment 4)
🏃 View run Improved XGBoost Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/525942e819e94328a11cd8c632969f5b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Improved XGBoost (SMOTE = False)

======================================================================
Loading Second Improved XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9473, F1 (macro): 0.8762, ROC AUC: 0.9744
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2717, 1: 20343}
  -> MLflow run id: f6b326dda1254829b4f78432a17c7771 (experiment 4)
🏃 View run Second Improved XGBoost Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/f6b326dda1254829b4f78432a17c7771
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Second Improved XGBoost (SMOTE = False)

======================================================================
Loading Third Improved XGBoost...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9475, F1 (macro): 0.8774, ROC AUC: 0.9745
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2749, 1: 20311}
  -> MLflow run id: 5a62d15eec494e80820ed8946cb0ec34 (experiment 4)
🏃 View run Third Improved XGBoost Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/5a62d15eec494e80820ed8946cb0ec34
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Third Improved XGBoost (SMOTE = False)

======================================================================
Loading Logistic Regression...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.8754, F1 (macro): 0.4668, ROC AUC: 0.6589
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {1: 23060}
  -> MLflow run id: aa010007b7e84654a2b1da5e0262a017 (experiment 4)
🏃 View run Logistic Regression Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/aa010007b7e84654a2b1da5e0262a017
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Logistic Regression (SMOTE = False)

======================================================================
Loading Logistic Regression SMOTE...
  -> Pipeline includes scaler: Using original 'X_test' (pipeline will scale)
  -> Accuracy: 0.4618, F1 (macro): 0.4159, ROC AUC: 0.6553
  -> Sample preds (first 10): [0, 1, 0, 1, 0, 0, 0, 1, 0, 1]
  -> Unique pred counts: {0: 13727, 1: 9333}
  -> MLflow run id: cbc8f284a2a7402482847035dedfedb1 (experiment 4)
🏃 View run Logistic Regression SMOTE Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/cbc8f284a2a7402482847035dedfedb1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Logistic Regression SMOTE (SMOTE = True)

======================================================================
Loading Random Forest...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.9416, F1 (macro): 0.8701, ROC AUC: 0.9707
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 3077, 1: 19983}
  -> MLflow run id: e2e7111ff82b4165b2f587e61ffb951f (experiment 4)
🏃 View run Random Forest Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/e2e7111ff82b4165b2f587e61ffb951f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Random Forest (SMOTE = False)

======================================================================
Loading Random Forest SMOTE...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.9365, F1 (macro): 0.8630, ROC AUC: 0.9711
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 3297, 1: 19763}
  -> MLflow run id: 42fa8e978e76427d97cfa6d415d5905c (experiment 4)
🏃 View run Random Forest SMOTE Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/42fa8e978e76427d97cfa6d415d5905c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Random Forest SMOTE (SMOTE = True)

======================================================================
Loading Random Forest Improved...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.9454, F1 (macro): 0.8727, ROC AUC: 0.9732
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2755, 1: 20305}
  -> MLflow run id: 0623c7f6ea954c6fbbc77b36d7b241b2 (experiment 4)
🏃 View run Random Forest Improved Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/0623c7f6ea954c6fbbc77b36d7b241b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Random Forest Improved (SMOTE = False)

======================================================================
Loading ANN...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.9383, F1 (macro): 0.8420, ROC AUC: 0.9644
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2179, 1: 20881}
  -> MLflow run id: 23bd505107014d04bc6f220c995b50e2 (experiment 4)
🏃 View run ANN Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/23bd505107014d04bc6f220c995b50e2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged ANN (SMOTE = False)

======================================================================
Loading ANN Weighted...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8762, F1 (macro): 0.7867, ROC AUC: 0.9635
  -> Sample preds (first 10): [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 5249, 1: 17811}
  -> MLflow run id: fe8e4fb2384744618ede8dfa88d80068 (experiment 4)
🏃 View run ANN Weighted Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/fe8e4fb2384744618ede8dfa88d80068
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged ANN Weighted (SMOTE = False)

======================================================================
Loading ANN SMOTE...
  -> Data type = 'scaled': Using 'X_test_scaled'
  -> Accuracy: 0.8902, F1 (macro): 0.8025, ROC AUC: 0.9631
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 4816, 1: 18244}
  -> MLflow run id: d1ec2785f72e4cf5b4d9c2e60adce519 (experiment 4)
🏃 View run ANN SMOTE Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/d1ec2785f72e4cf5b4d9c2e60adce519
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged ANN SMOTE (SMOTE = True)

======================================================================
Loading Stacking Classifier...
  -> Stacking Classifier: Using original 'X_test' (trained that way)
  -> Accuracy: 0.9481, F1 (macro): 0.8739, ROC AUC: 0.9737
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2493, 1: 20567}
  -> MLflow run id: 34ade0a5a1444378a7e6bbde1d1559c0 (experiment 4)
🏃 View run Stacking Classifier Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/34ade0a5a1444378a7e6bbde1d1559c0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Stacking Classifier (SMOTE = False)

======================================================================
Loading Second Stacking Classifier...
  -> Data type = 'original': Using 'X_test'
  -> Accuracy: 0.9475, F1 (macro): 0.8718, ROC AUC: 0.9736
  -> Sample preds (first 10): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  -> Unique pred counts: {0: 2465, 1: 20595}
  -> MLflow run id: 8529393bd3df4b9eb1bc545e58c10454 (experiment 4)
🏃 View run Second Stacking Classifier Binary (Both States) at: http://127.0.0.1:5000/#/experiments/4/runs/8529393bd3df4b9eb1bc545e58c10454
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Logged Second Stacking Classifier (SMOTE = False)

======================================================================
Cross-model prediction overlap:
  - KNN vs KNN SMOTE: identical fraction = 0.924
  - KNN vs XGBoost: identical fraction = 0.965
  - KNN vs XGBoost SMOTE: identical fraction = 0.914
  - KNN vs Improved XGBoost: identical fraction = 0.965
  - KNN vs Second Improved XGBoost: identical fraction = 0.963
  - KNN vs Third Improved XGBoost: identical fraction = 0.962
  - KNN vs Logistic Regression: identical fraction = 0.892
  - KNN vs Logistic Regression SMOTE: identical fraction = 0.471
  - KNN vs Random Forest: identical fraction = 0.957
  - KNN vs Random Forest SMOTE: identical fraction = 0.951
  - KNN vs Random Forest Improved: identical fraction = 0.965
  - KNN vs ANN: identical fraction = 0.960
  - KNN vs ANN Weighted: identical fraction = 0.878
  - KNN vs ANN SMOTE: identical fraction = 0.895
  - KNN vs Stacking Classifier: identical fraction = 0.969
  - KNN vs Second Stacking Classifier: identical fraction = 0.966
  - KNN SMOTE vs XGBoost: identical fraction = 0.916
  - KNN SMOTE vs XGBoost SMOTE: identical fraction = 0.933
  - KNN SMOTE vs Improved XGBoost: identical fraction = 0.916
  - KNN SMOTE vs Second Improved XGBoost: identical fraction = 0.922
  - KNN SMOTE vs Third Improved XGBoost: identical fraction = 0.923
  - KNN SMOTE vs Logistic Regression: identical fraction = 0.822
  - KNN SMOTE vs Logistic Regression SMOTE: identical fraction = 0.462
  - KNN SMOTE vs Random Forest: identical fraction = 0.936
  - KNN SMOTE vs Random Forest SMOTE: identical fraction = 0.939
  - KNN SMOTE vs Random Forest Improved: identical fraction = 0.927
  - KNN SMOTE vs ANN: identical fraction = 0.903
  - KNN SMOTE vs ANN Weighted: identical fraction = 0.916
  - KNN SMOTE vs ANN SMOTE: identical fraction = 0.926
  - KNN SMOTE vs Stacking Classifier: identical fraction = 0.920
  - KNN SMOTE vs Second Stacking Classifier: identical fraction = 0.918
  - XGBoost vs XGBoost SMOTE: identical fraction = 0.918
  - XGBoost vs Improved XGBoost: identical fraction = 0.993
  - XGBoost vs Second Improved XGBoost: identical fraction = 0.987
  - XGBoost vs Third Improved XGBoost: identical fraction = 0.986
  - XGBoost vs Logistic Regression: identical fraction = 0.894
  - XGBoost vs Logistic Regression SMOTE: identical fraction = 0.475
  - XGBoost vs Random Forest: identical fraction = 0.968
  - XGBoost vs Random Forest SMOTE: identical fraction = 0.958
  - XGBoost vs Random Forest Improved: identical fraction = 0.979
  - XGBoost vs ANN: identical fraction = 0.966
  - XGBoost vs ANN Weighted: identical fraction = 0.876
  - XGBoost vs ANN SMOTE: identical fraction = 0.894
  - XGBoost vs Stacking Classifier: identical fraction = 0.990
  - XGBoost vs Second Stacking Classifier: identical fraction = 0.991
  - XGBoost SMOTE vs Improved XGBoost: identical fraction = 0.919
  - XGBoost SMOTE vs Second Improved XGBoost: identical fraction = 0.929
  - XGBoost SMOTE vs Third Improved XGBoost: identical fraction = 0.930
  - XGBoost SMOTE vs Logistic Regression: identical fraction = 0.813
  - XGBoost SMOTE vs Logistic Regression SMOTE: identical fraction = 0.468
  - XGBoost SMOTE vs Random Forest: identical fraction = 0.942
  - XGBoost SMOTE vs Random Forest SMOTE: identical fraction = 0.947
  - XGBoost SMOTE vs Random Forest Improved: identical fraction = 0.931
  - XGBoost SMOTE vs ANN: identical fraction = 0.902
  - XGBoost SMOTE vs ANN Weighted: identical fraction = 0.932
  - XGBoost SMOTE vs ANN SMOTE: identical fraction = 0.944
  - XGBoost SMOTE vs Stacking Classifier: identical fraction = 0.920
  - XGBoost SMOTE vs Second Stacking Classifier: identical fraction = 0.919
  - Improved XGBoost vs Second Improved XGBoost: identical fraction = 0.988
  - Improved XGBoost vs Third Improved XGBoost: identical fraction = 0.987
  - Improved XGBoost vs Logistic Regression: identical fraction = 0.893
  - Improved XGBoost vs Logistic Regression SMOTE: identical fraction = 0.473
  - Improved XGBoost vs Random Forest: identical fraction = 0.968
  - Improved XGBoost vs Random Forest SMOTE: identical fraction = 0.959
  - Improved XGBoost vs Random Forest Improved: identical fraction = 0.980
  - Improved XGBoost vs ANN: identical fraction = 0.965
  - Improved XGBoost vs ANN Weighted: identical fraction = 0.876
  - Improved XGBoost vs ANN SMOTE: identical fraction = 0.894
  - Improved XGBoost vs Stacking Classifier: identical fraction = 0.989
  - Improved XGBoost vs Second Stacking Classifier: identical fraction = 0.990
  - Second Improved XGBoost vs Third Improved XGBoost: identical fraction = 0.994
  - Second Improved XGBoost vs Logistic Regression: identical fraction = 0.882
  - Second Improved XGBoost vs Logistic Regression SMOTE: identical fraction = 0.478
  - Second Improved XGBoost vs Random Forest: identical fraction = 0.974
  - Second Improved XGBoost vs Random Forest SMOTE: identical fraction = 0.965
  - Second Improved XGBoost vs Random Forest Improved: identical fraction = 0.981
  - Second Improved XGBoost vs ANN: identical fraction = 0.960
  - Second Improved XGBoost vs ANN Weighted: identical fraction = 0.887
  - Second Improved XGBoost vs ANN SMOTE: identical fraction = 0.904
  - Second Improved XGBoost vs Stacking Classifier: identical fraction = 0.986
  - Second Improved XGBoost vs Second Stacking Classifier: identical fraction = 0.986
  - Third Improved XGBoost vs Logistic Regression: identical fraction = 0.881
  - Third Improved XGBoost vs Logistic Regression SMOTE: identical fraction = 0.477
  - Third Improved XGBoost vs Random Forest: identical fraction = 0.974
  - Third Improved XGBoost vs Random Forest SMOTE: identical fraction = 0.966
  - Third Improved XGBoost vs Random Forest Improved: identical fraction = 0.981
  - Third Improved XGBoost vs ANN: identical fraction = 0.958
  - Third Improved XGBoost vs ANN Weighted: identical fraction = 0.888
  - Third Improved XGBoost vs ANN SMOTE: identical fraction = 0.905
  - Third Improved XGBoost vs Stacking Classifier: identical fraction = 0.985
  - Third Improved XGBoost vs Second Stacking Classifier: identical fraction = 0.984
  - Logistic Regression vs Logistic Regression SMOTE: identical fraction = 0.405
  - Logistic Regression vs Random Forest: identical fraction = 0.867
  - Logistic Regression vs Random Forest SMOTE: identical fraction = 0.857
  - Logistic Regression vs Random Forest Improved: identical fraction = 0.881
  - Logistic Regression vs ANN: identical fraction = 0.906
  - Logistic Regression vs ANN Weighted: identical fraction = 0.772
  - Logistic Regression vs ANN SMOTE: identical fraction = 0.791
  - Logistic Regression vs Stacking Classifier: identical fraction = 0.892
  - Logistic Regression vs Second Stacking Classifier: identical fraction = 0.893
  - Logistic Regression SMOTE vs Random Forest: identical fraction = 0.476
  - Logistic Regression SMOTE vs Random Forest SMOTE: identical fraction = 0.476
  - Logistic Regression SMOTE vs Random Forest Improved: identical fraction = 0.477
  - Logistic Regression SMOTE vs ANN: identical fraction = 0.472
  - Logistic Regression SMOTE vs ANN Weighted: identical fraction = 0.447
  - Logistic Regression SMOTE vs ANN SMOTE: identical fraction = 0.469
  - Logistic Regression SMOTE vs Stacking Classifier: identical fraction = 0.474
  - Logistic Regression SMOTE vs Second Stacking Classifier: identical fraction = 0.474
  - Random Forest vs Random Forest SMOTE: identical fraction = 0.976
  - Random Forest vs Random Forest Improved: identical fraction = 0.984
  - Random Forest vs ANN: identical fraction = 0.949
  - Random Forest vs ANN Weighted: identical fraction = 0.900
  - Random Forest vs ANN SMOTE: identical fraction = 0.916
  - Random Forest vs Stacking Classifier: identical fraction = 0.974
  - Random Forest vs Second Stacking Classifier: identical fraction = 0.968
  - Random Forest SMOTE vs Random Forest Improved: identical fraction = 0.972
  - Random Forest SMOTE vs ANN: identical fraction = 0.942
  - Random Forest SMOTE vs ANN Weighted: identical fraction = 0.907
  - Random Forest SMOTE vs ANN SMOTE: identical fraction = 0.924
  - Random Forest SMOTE vs Stacking Classifier: identical fraction = 0.963
  - Random Forest SMOTE vs Second Stacking Classifier: identical fraction = 0.959
  - Random Forest Improved vs ANN: identical fraction = 0.959
  - Random Forest Improved vs ANN Weighted: identical fraction = 0.889
  - Random Forest Improved vs ANN SMOTE: identical fraction = 0.906
  - Random Forest Improved vs Stacking Classifier: identical fraction = 0.987
  - Random Forest Improved vs Second Stacking Classifier: identical fraction = 0.979
  - ANN vs ANN Weighted: identical fraction = 0.866
  - ANN vs ANN SMOTE: identical fraction = 0.884
  - ANN vs Stacking Classifier: identical fraction = 0.966
  - ANN vs Second Stacking Classifier: identical fraction = 0.966
  - ANN Weighted vs ANN SMOTE: identical fraction = 0.949
  - ANN Weighted vs Stacking Classifier: identical fraction = 0.878
  - ANN Weighted vs Second Stacking Classifier: identical fraction = 0.877
  - ANN SMOTE vs Stacking Classifier: identical fraction = 0.896
  - ANN SMOTE vs Second Stacking Classifier: identical fraction = 0.894
  - Stacking Classifier vs Second Stacking Classifier: identical fraction = 0.990